### ISSUE TITLE
文章页面弹框提示错误。

### ISSUE THREAD

**Issue by IfFlyOverGrass** [smart-signature/smart-signature-future#100]
环境：生产机
问题重现方法：点击打赏按钮，弹出浏览器默认输入框，提示输入打赏金额。
此时无论点击确定还是取消，均会提示请输入正确金额。
理想的结果：点击取消，输入框消失。

**Comment by IfFlyOverGrass** [comment]
环境：生产机
问题重现方法：点击分享按钮，复制到剪贴板的链接不包含URL头“https://”，这样粘贴出去的链接会不能直接点击。
理想的结果：复制到剪贴板的链接包含“https://”

**Comment by guanchao71** [comment]
> 环境：生产机
> 问题重现方法：点击打赏按钮，弹出浏览器默认输入框，提示输入打赏金额。
> 此时无论点击确定还是取消，均会提示请输入正确金额。
> 理想的结果：点击取消，输入框消失。

测试重现：
在输入金额后，点击确定可以打赏。（未重现bug）
点击取消后会弹出提示金额输入错误。（这个问题不大，可以标P3）

**Comment by yukiexe** [comment]
> 点击打赏按钮 ...

只是還沒做全

**Comment by yukiexe** [comment]
>https:// 問題

#102 解決了

**Comment by yukiexe** [comment]
第 n 次來看了，解決了嗎？
#106 #94 #4
