### ISSUE TITLE
智能签名 - 首页 规则文案

### ISSUE THREAD

**Issue by aDappDeveloper** [smart-signature/smart-signature-future#103]
下面的文章就是规则

**Comment by aDappDeveloper** [comment]
https://shimo.im/docs/yrabdlA1GWsEynvq

**Comment by Deasoso** [comment]
了解，如果需要我可以参与合约工作。【似乎写完了？

**Comment by guanchao71** [comment]
> 了解，如果需要我可以参与合约工作。【似乎写完了？

合约工作？

**Comment by Deasoso** [comment]
> > 了解，如果需要我可以参与合约工作。【似乎写完了？
> 
> 合约工作？

哦我似乎理解错了= =我的意思是之前我不太了解流程现在了解了，才发现是首页给玩家看的规则文案。
那文案交给你们吧。

**Comment by xiaotiandada** [comment]
这样的形式是否可以，还需要再调整一下嘛

![image](https://user-images.githubusercontent.com/24250627/54708535-8de3f480-4b7e-11e9-8dae-517b1c3ee9c9.png)

**Comment by guanchao71** [comment]
> 这样的形式是否可以，还需要再调整一下嘛

没有问题，可以提交。

**Comment by lychees** [comment]
Closed via https://github.com/smart-signature/smart-signature-future/pull/128.
