### ISSUE TITLE
从前端隐藏部分文章的功能

### ISSUE THREAD

**Issue by aDappDeveloper** [smart-signature/smart-signature-future#105]
把用来测试的文章/违规的文章从前端隐藏掉

**Comment by guanchao71** [comment]
3月22号MVP 版本可以发布之前处理就可

**Comment by yukiexe** [comment]
問題來了，哪些是測試的文章呢？
我只能用日期一刀切了 weeeee

**Comment by guanchao71** [comment]
> 問題來了，哪些是測試的文章呢？
> 我只能用日期一刀切了 weeeee

这个版本可以，可是需要解决在后续有外人在使用的情况下，我们测试会不会干扰，，，感觉问题也不大。

**Comment by yukiexe** [comment]
到時候訂個測試的參數還是啥的是小事
不然給你們一個固定範本複製好了 233 超好過濾

**Comment by yukiexe** [comment]
publish 有合約的 action 內有時間戳
後端大概有記吧，要查下
ipfs 那邊我猜鐵定有
拿一種去過濾就行了

**Comment by yukiexe** [comment]
從 2019-03-21T00:00:00 之後發的才會顯示 #148

**Comment by yukiexe** [comment]
已合併，測試沒問題就 close 吧

**Comment by yukiexe** [comment]
新想法：弄個 json 讀 json 去做 ban list 設定

**Comment by yukiexe** [comment]
跟友司員工討論過後呢，想想還是得有個後台管理
最基本是 ban list 的 json 從後端拿
如何更新設定再說，看是弄個有 UI 的還是直接檔案更新等等

@AkemiKusane 提個新需求:
後端存個 ban list 的 json ，讓前端可以跟後端拿名單做處理
格式:
banList: {
   ids:[ {siginId: 000, reason: 'i dont like it.' }, ], // 內含數個
   beforeTheTime:[ { time: 'xxx' } ], // 第二種規則，指定時間之前
}

**Comment by lychees** [comment]
Obsolete.
