### ISSUE TITLE
雕刻界面细节

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#106]
主要是前端的一些细节活。按照蓝湖上面的样式来进行对照调整。

**Comment by guanchao71** [comment]
https://lanhuapp.com/url/Jhc37
这里是设计图

**Comment by yukiexe** [comment]
挑三頁最重要的，先做
這個挺費時的

編輯器顯示的不能算

**Comment by xiaotiandada** [comment]
> 挑三頁最重要的，先做
> 這個挺費時的
> 
> 編輯器顯示的不能算

问题来了 挑那三个 我先调调首页

**Comment by yukiexe** [comment]
首頁先，好！

**Comment by yukiexe** [comment]
@guanchao71 公開設計稿行嗎？

**Comment by yukiexe** [comment]
這個 issue 太空泛，請統一在目前進度記錄個別進度和問題
