### ISSUE TITLE
[Bug] 无法裂变打赏文章

### ISSUE THREAD

**Issue by aDappDeveloper** [smart-signature/smart-signature-future#109]
桌面钱包直接打赏作者 ✅

TP钱包 – 从文章链接点进去打赏 × 不可

桌面钱包通过用户邀请链接打赏 × 不可

手机钱包通过用户邀请链接打赏 × 不可

可与Issue #97 一并修复？

报错消息：

error:"{\"code\":500,\"message\":\"Internal Service Error\",\"error\":{\"code\":3050003,\"name\":\"eosio_assert_message_exception\",\"what\":\"eosio_assert_message assertion failure\",\"details\":[{\"message\":\"assertion failure with message: this signature is not exist\",\"file\":\"wasm_interface.cpp\",\"line_number\":924,\"method\":\"eosio_assert\"},{\"message\":\"pending console output: \",\"file\":\"apply_context.cpp\",\"line_number\":72,\"method\":\"exec_one\"}]}}"

**Comment by yukiexe** [comment]
打賞的是哪篇文章?

**Comment by aDappDeveloper** [comment]
https://sign-dev.dravatar.xyz/article/QmZEe2nimeEHbvwTpNLUYg8ZgWstQy7a2QyNUk734jKf6y?invite=eosdapplover 



> 打賞的是哪篇文章?

https://sign-dev.dravatar.xyz/article/QmZEe2nimeEHbvwTpNLUYg8ZgWstQy7a2QyNUk734jKf6y?invite=eosdapplover

**Comment by yukiexe** [comment]
應該是 #84 的問題
也就是直接點開文章的連結而非經由首頁的話，其實並沒有登陸

**Comment by guanchao71** [comment]
#131 之后已经可以愉快得打赏了，但是当前通过邀请链接去打赏的时候，经过测试，EOS确实是打赏到了本文作者的钱包里面，并没有给到邀请者。

**Comment by yukiexe** [comment]
合約的bug，已解決 https://github.com/smart-signature/smart-signature-EOS-contract/commit/0849fa21b597d75703509f91fac4221ad2ce5a92

群裡好像驗證了，驗證過了就 close 吧
