### ISSUE TITLE
Backend 回報區

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#114]
**https://github.com/smart-signature/smart-signature-backend**

https://github.com/smart-signature/smart-signature-backend/blob/master/doc.md

由於在群裡說可能會錯過，就這裡回報改了甚麼，有甚麼 API 可用
這樣可以直接貼 commits 的連結

**Comment by lychees** [comment]
https://github.com/smart-signature/smart-signature-future/pull/117
Here you can find demo code. @yukiexe  @Deasoso

**Comment by ganjingcun** [comment]
文章被阅读次数统计 #51 

新增 阅读次数统计的api : 
带上access_token请求，会记录读者名字：

curl -H "x-access-token: your_access_token"  -X POST http://api.smartsignature.io/post/show/QmfNHT4eaQ8XGr1kYXZFGEGtkGkr93H8of1vKc5L16ThSK

或者直接调用，算作匿名用户：

curl  -X POST http://api.smartsignature.io/post/show/QmfNHT4eaQ8XGr1kYXZFGEGtkGkr93H8of1vKc5L16ThSK

--------

阅读次数字段为 read ，在获取单篇文章的返回数据里 ：
ex：
http://api.smartsignature.io/post/QmfNHT4eaQ8XGr1kYXZFGEGtkGkr93H8of1vKc5L16ThSK

**Comment by ganjingcun** [comment]
新增 author filter 到 posts api。可以根据作者筛选文章。https://github.com/smart-signature/smart-signature-backend/commit/cd2457daf5c19cb5047e39d2e1d1bc0e3bdd0cdd

#137

**Comment by Deasoso** [comment]
> 新增 author filter 到 posts api。可以根据作者筛选文章。[smart-signature/smart-signature-backend@cd2457d](https://github.com/smart-signature/smart-signature-backend/commit/cd2457daf5c19cb5047e39d2e1d1bc0e3bdd0cdd)
> 
> #137

我已经在前端筛选了= =先这样放着吧。

**Comment by Deasoso** [comment]
现在需要筛选打赏者，无法从目前的文章列表返回值中获取。
返回文章的属性需要一个打赏者列表。

**Comment by Deasoso** [comment]
最好提供一个当前accesstoken是否可用的接口？

**Comment by ganjingcun** [comment]
> 最好提供一个当前accesstoken是否可用的接口？
> 因为每次刷新从后端读取accesstoken都需要调用钱包，操作比较麻烦。

获取成功进行缓存的时候。存时间戳即可。过期的话自动重新获取。

**Comment by ganjingcun** [comment]
新增api
#### 获取打赏列表

* GET /shares

* 参数 :
* page: 页数，默认第一页
* user: 指定用户
* signid: 指定文章

获取打赏列表，支持使用user和signid进行筛选。

**Comment by Deasoso** [comment]
> 新增api
> 
> #### 获取打赏列表
> * GET /shares
> * 参数 :
> * page: 页数，默认第一页
> * user: 指定用户
> * signid: 指定文章
> 
> 获取打赏列表，支持使用user和signid进行筛选。

打赏列表返回的文章没有标题，需要补充。

**Comment by ganjingcun** [comment]
> > 新增api
> > #### 获取打赏列表
> > 
> > * GET /shares
> > * 参数 :
> > * page: 页数，默认第一页
> > * user: 指定用户
> > * signid: 指定文章
> > 
> > 获取打赏列表，支持使用user和signid进行筛选。
> 
> 打赏列表返回的文章没有标题，需要补充。

那个是打赏队列数据。文章请用下面的

#### 获取支持过的文章列表

* GET /supports

* 参数 :
* page: 页数，默认第一页
* user: 指定用户

获取支持过的文章列表，支持使用user进行筛选。

请求示例: 
* curl -X GET https://api.smartsignature.io/post/supports?user=flyovergross

**Comment by ganjingcun** [comment]
请求示例: 
* curl -X GET https://api.smartsignature.io/supports?user=flyovergross

**Comment by lychees** [comment]
Can we close this for now?
上次有人汇报还是 9days ago，我们直接去 backend repo 看就好了，没有必要出现在这里。
