### ISSUE TITLE
现存但是不影响MVP的问题

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#135]
- [x] 打赏之后如果不主动刷新页面，打赏按钮不会切换为已打赏状态
- [x] 在电脑上打赏之后，分享链接到手机上，在TP钱包中直接打开链接之后，并不会直接显示出“已打赏”状态。但是打赏操作之后会失败。
- [x] 资产明细的排序应该由近到远向下排列
- [x] 资产明细页面滚到最下会一直有文字提示“加载中”
- [x] 资产明细页面的赞赏支出的数据会超框，需要加以控制。默认仅显示小数点后两位，总位数最多8个字符+5203.66；-2.03K；+132445
- [x] 每次进入资产明细页面的时候，都会默认加载出来两条有明确数据的明细数据，可以初始化，但是不要显示无效数据，也会感觉像是出错了。
- [x] ~~不管有没有打赏，分享的邀请链接都带有ID显示，（好像不会影响功能。）~~
- [x] ~~后续版本需要将开发环境和生产环境做隔离处理~~ (請移至專門討論 issue

**Comment by yukiexe** [comment]
你標個數字好引用和標記

**Comment by yukiexe** [comment]
> 9. 后续版本需要将开发环境和生产环境做隔离处理

分支上是有的，不過 ipfs 是存在外面所以很尷尬

**Comment by yukiexe** [comment]
> 8. 不管有没有打赏，分享的邀请链接都带有ID显示，（好像不会影响功能。）

本來就是這樣設計的，不信你問 @lychees

**Comment by yukiexe** [comment]
> 5. 资产明细页面滚到最下会一直有文字提示“加载中”

@xiaotiandada 這給你改，參照其他頁改就行

**Comment by yukiexe** [comment]
> 1. 打赏之后如果不主动刷新页面，打赏按钮不会切换为已打赏状态

我看看怎麼改

**Comment by xiaotiandada** [comment]
> > 1. 资产明细页面滚到最下会一直有文字提示“加载中”
> 
> @xiaotiandada 這些給你改，5. 參照其他頁改就行

好的

**Comment by yukiexe** [comment]
> 1. 打赏之后如果不主动刷新页面，打赏按钮不会切换为已打赏状态

#135

**Comment by yukiexe** [comment]
> 6. 资产明细页面的赞赏支出的数据会超框，需要加以控制。默认仅显示小数点后两位，总位数最多8个字符+5203.66；-2.03K；+132445

Outdated ，請更新最新狀態

**Comment by yukiexe** [comment]
> 7. 每次进入资产明细页面的时候，都会默认加载出来两条明细数据

這叫初始化數據，很多 app 加載中都看的到的，不算 bug
尤其讀鍊上的 data 不快，沒有這個會讓人覺得壞了
本來要配合右邊的顯示圖做設定的，但是一直沒有被給到詳細設計，就這麼放著了

**Comment by yukiexe** [comment]
> 2. 资产明细的排序应该由近到远向下排列

恩...我記得沒錯呀？可能我記錯或是改時間顯示的時候改錯了
如果是原始 data 反了，他是個數組，反過來讀即可

**Comment by yukiexe** [comment]
搬運 from #24 

- 跳框選 app 分享

因為現在都在手機錢包裡看，內置瀏覽器的版本也不定且難處理，大概不太可能做

參考可用資源
https://github.com/smart-signature/smart-signature-future/issues/24#issuecomment-474049577

**Comment by yukiexe** [comment]
並沒有全部完成，reopen

**Comment by yukiexe** [comment]
> 5. 资产明细页面滚到最下会一直有文字提示“加载中”
done /w #149

**Comment by yukiexe** [comment]
打賞狀態的請整合到同一個 issue 裡
