### ISSUE TITLE
follow/unfollow相关，需要自动登录。

### ISSUE THREAD

**Issue by Deasoso** [smart-signature/smart-signature-future#143]
现在follow/unfollow前，需要到publish页面执行authDemo()以获取accesstoken。
这显然是不合理的，希望用户在进入首页，登录后就能自动从后端获取token。

**Comment by ganjingcun** [comment]
accesstoken 只需获取一次保存。 然后有效期是7天。

把authDemo改写下。它只是个demo - -

**Comment by yukiexe** [comment]
#148
