### ISSUE TITLE
'insecure stylesheet' broke the Demo site

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#145]
<img width="610" alt="屏幕快照 2019-03-22 上午11 19 40" src="https://user-images.githubusercontent.com/2507027/54798577-68490f00-4c94-11e9-8c6f-536e83e48dfb.png">

I cannot open any article page in the Demo website. It seems to me that some one import some CSS file from some insecure http source (maybe from bootstrap?).

**Comment by yukiexe** [comment]
好的，我覺得我找不到
而且得部屬到 testing 才知道有沒有修到，尷尬

**Comment by yukiexe** [comment]
可能得從 pr 推估問題在哪個了

**Comment by yukiexe** [comment]
@import url(https://cdn.bootcss.com/github-markdown-css/2.10.0/github-markdown.min.css);
https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.9.0/github-markdown.css

抓到兩條疑似會衝突的，可是我本地弄出來都是 https

**Comment by yukiexe** [comment]
果然 mavon-editor 裡面有份 github-markdown.min.css
還有 github.min.css, googlecode.min.css ，引用很多捏

**Comment by yukiexe** [comment]
KaTeX css 是數學公式的
剩一個 hightlight ，用的是 github.min.css

**Comment by lychees** [comment]
Confirmed. Good job.
