### ISSUE TITLE
打赏后，误使用字符串连接作为加法更新打赏金额。

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#147]
<img width="209" alt="屏幕快照 2019-03-22 上午11 56 13" src="https://user-images.githubusercontent.com/2507027/54799809-b7de0980-4c99-11e9-9c96-25484cd730fb.png">

btw, 直接在这里写一个金额。。。谁一上来就知道它代表什么意思啊？

**Comment by guanchao71** [comment]
> btw, 直接在这里写一个金额。。。谁一上来就知道它代表什么意思啊？

第一版UI设计用了图标来表示含义，可能不能给用户直观理解。

**Comment by yukiexe** [comment]
#148
