### ISSUE TITLE
赞赏数据加载和赞赏按钮的多状态设置

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#151]
<img width="588" alt="屏幕快照 2019-03-22 下午8 11 56" src="https://user-images.githubusercontent.com/2507027/54822125-35783880-4cdf-11e9-86e6-84d4e46231ae.png">

<img width="673" alt="屏幕快照 2019-03-22 下午8 12 01" src="https://user-images.githubusercontent.com/2507027/54822126-36a96580-4cdf-11e9-94a7-24982cc12c38.png">

（似乎林可之前有提到，目前还没有解决，这里提一下）

- [x] 当在页面打赏进行之后，金额已经刷新，但打赏的按钮并没有立即变成 disable，需要刷新页面才可以看到 disable。

- [x] 赞赏按钮在载入时候有延迟，需要增加loading状态

- [x] 打赏金额载入有延迟，载入之前显示为 0，似乎显示 loading 会更好一些（类似的问题在 Kyubeydex 中也存在）。

**Comment by yukiexe** [comment]
> 打赏金额载入有延迟，载入之前显示为 0，似乎显示 loading 会更好一些

淘x 都沒在管的，很多網站也都沒在管的
說真的挺無關緊要的
不知道能不能統一指向一個 string loading 省事一點

然後會有延遲是因為現場抓 1.2mb的資料現場算 xDDD

**Comment by yukiexe** [comment]
都給後端存儲與整理當然會快很多，不過這功能可能就得下週三出來了

**Comment by yukiexe** [comment]
#156

**Comment by guanchao71** [comment]
#166

**Comment by IfFlyOverGrass** [comment]
#170

**Comment by yukiexe** [comment]
#186
