### ISSUE TITLE
优先处理的小毛病

### ISSUE THREAD

**Issue by chitutu** [smart-signature/smart-signature-future#154]
- [x] 需更新LOGO 
- [x] 系统时间有误
- [x] 文章页面：“打赏”按钮应改为”赞赏“
- [x] 文章页面文本：”总共赞赏 0.2100 EOS“ 改为 “本文共获 0.2100 EOS 赞赏” （之前没有提这个需要，更改一下可减少用户歧义）

**Comment by IfFlyOverGrass** [comment]
2已解决#152
3已解决#152
4已解决#152

**Comment by guanchao71** [comment]
> 1.更新LOGO

说明：将首页用户头像和用户页头像都替换成产品logo。这是在头像功能没有做好，logo没有正式安放位置之前，应该是最好的解决方案之一。

**Comment by yukiexe** [comment]
> 文章页面：“打赏”按钮应改为”赞赏“

需求在哪提的？？？
如果在 issue 要提需求的話請標明，並不要與 小毛病 或是 bug 在同一個裡面提

**Comment by yukiexe** [comment]
全解決

**Comment by guanchao71** [comment]
@yukiexe 首页的临时头像也需要替换成为产品的logo。(总挂着岛的看起来怪异的很。
在头像编辑上传功能没做好之前，全都显示着产品的logo。
