### ISSUE TITLE
资产显示相关问题

### ISSUE THREAD

**Issue by chitutu** [smart-signature/smart-signature-future#155]
1/ 资产明细中，打赏顺序是反的；应改为最近打赏在最上面
2/ 资产明细 与 个人主页显示的创作收益不一致
3/ 待提现总是为0

**Comment by IfFlyOverGrass** [comment]
1已解决#152

**Comment by yukiexe** [comment]
> 资产明细 与 个人主页显示的创作收益不一致

歷史共業，资产明细的記錄是之後才加的，在那之前獲得的创作收益全是黑帳。上次還改了一輪 share 結構，也是 table 全清，player 表並沒有清，所以全是對不上帳的帳，就像隔壁某公司的帳一樣

**Comment by yukiexe** [comment]
然後問題帳號提供一下

**Comment by yukiexe** [comment]
个人主页显示的创作收益是"歷史"创作收益，也就是提現後不會減少的

**Comment by yukiexe** [comment]
沒有任何人提任何更新的需求，目前顯示的就是"歷史"创作收益

**Comment by yukiexe** [comment]
啊，算了

**Comment by yukiexe** [comment]
合併至 #52
