### ISSUE TITLE
【裂变系数】手动设置裂变系数功能

### ISSUE THREAD

**Issue by chitutu** [smart-signature/smart-signature-future#157]
当前写作时填写的裂变系数，不在合约&前端作出反馈，依旧默认是2；

**Comment by yukiexe** [comment]
查了一圈 f9b5769  ，是後端的問題：
前端有把作者填寫的裂变系数確實地送到後端，目前是後端在合約上 publish 的

**Comment by guanchao71** [comment]
预期效果
- 编辑文章时，前端默认显示为2，数据范围为1.0到5.0之间。
- 用户可手动输入调整数值大小，精确到小数点后1位。
- 使用正则验证输入的有效性。当用户清空输入框后，显示灰色字：请输入1.0到5..0之间的数值
文章发布之后，在文章底部正确显示用户输入的裂变系数数值

**Comment by guanchao71** [comment]
当前默认设定为2，并且锁定修改。
下一阶段应该会设计成一个滑动条的形式，让用户在一定范围内选择一个数值。

**Comment by guanchao71** [comment]
#319 已经有新的issue了
