### ISSUE TITLE
Page 首页

### ISSUE THREAD

**Issue by IfFlyOverGrass** [smart-signature/smart-signature-future#16]
于用户而言有两个版本：登陆后的页面，未登录的页面。（当然不一定要做两个页面啦）

- [ ] 未登录的页面具备跳转到**登录页面**的按钮。此后登录信息存于cookie。
- [x] 如果用户拥有EOS钱包可以直接唤起钱包来执行登录过程。
- [x] 用户登陆后可以看到自己账户的余额。
- [ ] 界面右上角有中英文切换按钮
- [ ] 登录的页面可以从个人昵称和头像处跳转到**个人主页**。
- [ ] 上方有搜索框。考虑到吸引用户，若用户无登录cookie则跳转到**登录页面**。（搜索框这个不急）
- [ ] 使用帮助（原玩法介绍）按钮可以跳转到**帮助页面**。
- [ ] 个人资料下面是文章列表，最多分享，最多支持页面。
- [ ] 文章列表目前做成随机从后台拿取文章（制作前端和API时请考虑会用到推荐算法的情况以便于后续开发）。
- [ ] 最多分享按照最近一周（时间以后可以做成方便修改的）分享数量排序。
- [ ] 最多支持按照最近一周分享数量排序。
- [ ] 点击创建文章按钮，弹出两个小按钮：快捷搬运和写文章。点击快捷搬运按钮跳转到**快捷搬运**页面，点击写文章按钮跳转到**创建文章**页面。

**Comment by IfFlyOverGrass** [comment]
补充：各位研发大佬们有啥要槽的一定要讲啊。

**Comment by lychees** [comment]
请参考交互原型：
https://lanhuapp.com/web/#/item/project/board/proto/edit?pid=a354b423-db6c-4497-8a91-14dc7915fd93&image_id=8139ba54-f2c5-4d42-99b9-86c583f0042c

**Comment by yukiexe** [comment]
原型可以公開嗎？？？

**Comment by yukiexe** [comment]
@IfFlyOverGrass 知道目前的分工與完成狀態嗎？還是需要給您留一份記錄

**Comment by lychees** [comment]
> 原型可以公開嗎？？？

我想可以吧，既然代码合约都公开了，就彻底一点啊。。（

**Comment by yukiexe** [comment]
跟公司的人商量一下啊，沒有選項的不叫商量
你這麼衝，我扛不住啊

**Comment by yukiexe** [comment]
交互原型有更新，請在該頁左上角選新版本作為參考

**Comment by yukiexe** [comment]
有新的進度 issue #45
未來功能要再補充開新的 issue 說
