### ISSUE TITLE
通过别人的邀请链接给自己文章赞赏  的处理方式不合理

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#167]
- [ ] **通过别人的邀请链接给自己文章赞赏的并发症**
- 现在作者通过别人的邀请链接赞赏自己的文章，钱会给到作者自己。这种处理方式显然是不合理的，相当于增加了一条额外的赞赏规则，增加了用户的理解成本（如无必要，勿增实体）。
- 并且发出邀请链接的用户会在资产明细中收到神秘的+0.0000EOS，并且虽然是+号，但是却显示为了绿色（正常绿色代表支出）非常难以理解。

**预期结果：当下只存在两条条赞赏的规则：**
- 通过谁的邀请链接赞赏，那么在对方已经赞赏过，且quota没有溢出的请情况下，钱一定会给到发出邀请链接的用户，只有溢出部分会给到作者。
- 直接访问文章地址或者通过作者自己的邀请链接访问的用户，所有赞赏资金都会给到作者。当邀请链接来自作者自己，收入也是归到创作收益里记录。

![image](https://user-images.githubusercontent.com/10827774/54878261-2ae7ab80-4e65-11e9-900a-3ea60e8027f4.png)

_Originally posted by @guanchao71 in https://github.com/smart-signature/smart-signature-future/issues/52#issuecomment-475947721_

**Comment by yukiexe** [comment]
> 现在作者通过别人的邀请链接赞赏自己的文章，钱会给到作者自己。这种处理方式显然是不合理的，相当于增加了一条额外的赞赏规则，增加了用户的理解成本

add share income 不給赞赏的人不然給誰？
剩下的還是給作者，這只是這兩者都是作者而已。
況且作者開小號讚賞還不是一樣？駁回

**Comment by guanchao71** [comment]
我在智能签名上发现了一篇好文章！https://sign-dev.dravatar.xyz/article/QmUSdEXq881vcBuBzG8QaKvLxYqj2xeP1KCaMUpJSUBvVw?invite=flyovergross 赞赏好文，分享有收益 ！

经错一轮测试确实已经是修好了先close掉了。不过我的记录中确实存在过+0.0000EOS的记录。
