### ISSUE TITLE
【待修复】当前创作收益和赞赏收益两项数据没有正确显示

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#168]
### 当前创作收益和赞赏收益两项数据没有正确显示：
- 创作收益显示的其实是待提现余额，而且没有*精度系数，显示的是个很大的数字
- 赞赏收益直接没有显示
![image](https://user-images.githubusercontent.com/10827774/54878602-ef031500-4e69-11e9-9abf-0e8f42af5d1f.png)

### 预期结果
1. - [ ] **创作收益数据显示包含：**
- 用户A直接访问问文章链接，赞赏的所有钱都属于作者的创作收益
- 用户A通过作者的邀请链接访问文章，赞赏的所有钱都属于作者的创作收益
- 用户A通过用户B的邀请链接访问文章，赞赏满足B的quota之后，溢出的赞赏资金都属于作者的创作收益

2. - [x] **赞赏收益数据显示包含：**
- 用户B通过用户A的邀请链接进行赞赏，在用户A的收益范围中的部分都算作赞赏收益

重点总结：收益归到哪个种类主要是看收益来源的文章作者是不是自己？如果是自己那就是创作收益，如果不是自己那就是赞赏收益。

_Originally posted by @guanchao71 in https://github.com/smart-signature/smart-signature-future/issues/52#issuecomment-475949395_

**Comment by guanchao71** [comment]
# 166
![image](https://user-images.githubusercontent.com/10827774/54894572-4bac1180-4ef6-11e9-8f08-1af3f25c84da.png)
看起来已经完成了，再有问题需要后续测试提出。先close掉。

**Comment by guanchao71** [comment]
创作收益&赞赏收益是历史数据，但是在我提现之后被清理掉了。
![image](https://user-images.githubusercontent.com/10827774/55101166-749ef300-50fe-11e9-8fc7-6f55fa108b6b.png)

**Comment by yukiexe** [comment]
藍湖請同步更新下最新 UI 設定
done /w #196

**Comment by lychees** [comment]
Confirmed.
