### ISSUE TITLE
赞赏按钮的多状态设计

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#177]
需要实现的功能：
赞赏按钮存在三个状态，加载中，赞赏，已赞赏。
#166 #170 
- [x] 在未获得当前赞赏状态的时候为加载中状态。
- [ ] 在未登录时显示为赞赏状态，点击后触发先登录后
- [x] 当点击赞赏按钮后，转换为加载中，同时唤起signature.js的support的操作。
- [x] 在这个过程中很可能出现因为余额不足，网络错误等而出现赞赏失败的情况，此时需要触发一个error
- [x] 在触发错误的同时将按钮恢复到可赞赏的状态。
- [x] 如果error没有触发，则将按钮状态设置成已赞赏的状态。

**Comment by yukiexe** [comment]
登陸是一整個有問題的部分，而不是只有按鈕顯示的問題
