### ISSUE TITLE
markdown 文章的排版。

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#185]
hackmd 无疑是一个非常好的参考，（可惜需要翻墙）
希望文章的排版可以和 hackmd align 上。

下面是同样的一段 markdown 在两边目前的 layout。

https://hackmd.io/s/S1XO6-v_E
https://sign-dev.dravatar.xyz/article/QmQFMCqYqRbcLncVH1U7za8pPmSgWgK7SiuiasxSjiQSrY

<img width="737" alt="屏幕快照 2019-03-26 下午6 44 31" src="https://user-images.githubusercontent.com/2507027/54991142-42ef3480-4ff7-11e9-94c6-c69f3a22f805.png">

<img width="755" alt="屏幕快照 2019-03-26 下午6 44 22" src="https://user-images.githubusercontent.com/2507027/54991572-2dc6d580-4ff8-11e9-88cb-a9263a82c227.png">

<img width="445" alt="屏幕快照 2019-03-28 下午6 38 05" src="https://user-images.githubusercontent.com/2507027/55151362-0e12e700-5189-11e9-998b-911c3448eeab.png">

https://sign-dev.dravatar.xyz/article/QmTzDcrXWfMuFgNYm2ZNxBvPR69B6PGGhGmxJ5Y8amgDpN?invite=minakokojima

可以看到无论是字体还是行间距都是 hackmd 的表现更好，
建议可以直接替换成 隔壁 CSS 文件。

**Comment by yukiexe** [comment]
可能的話，早上中午前交代工作或今晚交代明早的工作 @lychees

**Comment by yukiexe** [comment]
預計會與 #97 一起處理

**Comment by lychees** [comment]
<img width="445" alt="屏幕快照 2019-03-30 上午8 35 01" src="https://user-images.githubusercontent.com/2507027/55268644-ba0e1c80-52c6-11e9-8224-0c484f692215.png">

This issue seems to be fixed now.
Fell free to close it.

**Comment by shellteo** [comment]
done https://github.com/smart-signature/smart-signature-future/pull/201
