### ISSUE TITLE
赞赏列表尚存的问题

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#193]
1. - [x] **不能百分百显示所有人的赞赏留言**
![image](https://user-images.githubusercontent.com/10827774/55103538-9ea6e400-5103-11e9-945c-59bc0418536d.png)
预期结果：可以显示所有的留言
2. - [x] **打赏列表页面刷新之后就会进入原型页面**
![image](https://user-images.githubusercontent.com/10827774/55103499-820aac00-5103-11e9-886d-2dea258532a5.png)
预期结果：单独打开页面URL或者刷新页面都只会显示对应的列表页面。

**Comment by guanchao71** [comment]
留个思考：既然打赏页面是可以分享出去的，那么head部分的返回按钮就是没有意义的。需要设计入口可以返回到文章页面。这样即便是分享了打赏列表页面出去，别人看到也可以返回去看文章。
如果可以在打赏列表页面的返回按钮中，记录原文的链接的话，就可以实现退回文章的功能了。具体怎么设计还需要仔细考虑。

**Comment by guanchao71** [comment]
**打赏列表版：**
谁在什么时候，通过谁的邀请链接，打上了多少钱，留了什么言。。
**收支明细版（需要仔细设计）：**
谁在什么时候，邀请你去哪篇文章，打上了多少钱
**打赏时间轴版：**
谁在什么时候，通过谁的邀请链接，在哪篇文章，打上了多少钱，留了什么言。。

**Comment by guanchao71** [comment]
![image](https://user-images.githubusercontent.com/10827774/55107839-39f08700-510d-11e9-9102-dc52d2d1d403.png)

**Comment by yukiexe** [comment]
> 不能百分百显示所有人的赞赏留言

你們誤會了甚麼，那兩則空白是 comment 根本沒寫入，是空的。
用了舊版網頁輸入就會那樣

**Comment by yukiexe** [comment]
> 打赏页面是可以分享出去的

那就做成沒法分享出去吧

**Comment by yukiexe** [comment]
> 设计入口可以返回到文章页面

這當然沒問題，有需要考慮這麼多嗎？
一個按鈕就回去原文章頁面當然沒問題

是說，也就是所有的返回都沒用的意思，聽起來挺低能的，不過現況錢包生態好像也只能這樣。
是不是繞過這個問題就發達了？
我覺得實際上做起來也挺簡單的。
app 都能接收通知對吧？
那我們發個請求到特定地址，然後那邊轉發通知回手機上的 app ，然後手機app 按確認啥的。
再次轉發到我們的後端，後端叫前端，完成錢包授權。
也不用考慮在手機中的 chrome 裡如何叫在隔壁的 app 這個看似簡單其實很麻煩的事
