### ISSUE TITLE
【评论】赞赏评论内容不能被正确记录

### ISSUE THREAD

**Issue by aDappDeveloper** [smart-signature/smart-signature-future#215]
如下图所示，两次我都有在赞赏时写推荐语，都是用TP钱包，结果一次显示，一次不显示。
![IMG_9335](https://user-images.githubusercontent.com/44354447/55279346-0141ef00-5353-11e9-9f95-1ebcfb0a2a4b.PNG)
![IMG_9336](https://user-images.githubusercontent.com/44354447/55279347-01da8580-5353-11e9-8e6c-4152f0efbe11.PNG)

**Comment by aDappDeveloper** [comment]
#193 中有提到相同问题。

**Comment by AkemiKusane** [comment]
#217  看看这之后是不是好了，好了就关掉它吧

**Comment by yukiexe** [comment]
知道了問題了，按太快，請求都還沒送就換頁了，當然沒送成功...

**Comment by yukiexe** [comment]
現在水管接的太亂了，不好好整理這些問題只會一再出現...

**Comment by yukiexe** [comment]
POST https://api.smartsignature.io/post/comment 401

**Comment by AkemiKusane** [comment]
#284 测一下

**Comment by lychees** [comment]
Can we close this issue now?

**Comment by yukiexe** [comment]
沒錯，他又復活了

我推測又是 auth token 的問題

**Comment by yukiexe** [comment]
看看 #309 能不能解決這個問題，合併後需要繼續測試

**Comment by guanchao71** [comment]
> 似乎不是取得 authtoken 的問題
> 看看 #309 能不能解決這個問題，合併後需要繼續測試

@yukiexe 在PC端测试评论是可以被正确记录下来，但是在tp钱包上无法被记录下来。

**Comment by yukiexe** [comment]
本來，在網站或app或遊戲的登錄機制SOP設計上，會有登錄和登出。
但 dapp 生態要求自動登錄，但沒有登出，這樣是一種新的流程。
密碼學告訴我們不要設計自己的加密 func。
新的流程，需要縝密地設計，顯然我們沒做過。

在手機錢包登出，並不等於在 dapp 裡登出，因為 dapp 只會在要求簽名的時候才判斷有沒有連著錢包。
那加上了 access token ，在沒有登出階段的情況下，自然不會有登出銷毀這事

然後有人沒考慮要去取得新 access token for other user.
本來設計是每次都取一次新的，被修，然後就產生了不同人用同一個 access token 的蠢事

後端又沒有寫被拒是 token 過期還是對不上人頭
@AkemiKusane 跟後端說把反饋的 meg 完善一下

**Comment by AkemiKusane** [comment]
了解，需要列个单子

**Comment by guanchao71** [comment]
#323之后评论功能在PC和TP钱包上测试都已经正常。
