### ISSUE TITLE
【文案】运营提出新需求 - 修改点击“分享”按钮的文案

### ISSUE THREAD

**Issue by aDappDeveloper** [smart-signature/smart-signature-future#220]
原文案：

我在智能签名上发现了一篇好文章！http://smartsignature.io/article/QmRoUwGkwGLwwUnUQHnHptHnvzZ16LiuW6aR5YwP834GJD?invite=andoromedaio 赞赏好文，分享有收益 ！

新文案：

《文章标题》 by 作者名 + 短url + 赞赏好文，分享有收益 ！

**Comment by yukiexe** [comment]
@xiaotiandada 短url 的方案先提了再開工歐

**Comment by guanchao71** [comment]
测试环境已经测试通过。
