### ISSUE TITLE
单篇阅读量显示不正确

### ISSUE THREAD

**Issue by aDappDeveloper** [smart-signature/smart-signature-future#223]
用户非登录状态（或通过微信之类的打开文章），该文章阅读数量显示为0（实际100+），需要登录才能正确显示。

用户看到阅读量为0的文章会被吓跑，请尽快修复。

**Comment by aDappDeveloper** [comment]
好像是数据加载时间过长的原因，所以很长时间看到阅读量为0 。刚刚在非登录下打开，加载一段时间，又可以看到阅读量数据了。

**Comment by Deasoso** [comment]
收到。我检查一下

**Comment by Deasoso** [comment]
> 好像是数据加载时间过长的原因，所以很长时间看到阅读量为0 。刚刚在非登录下打开，加载一段时间，又可以看到阅读量数据了。

错误未复现，我这边在钱包上锁后，未登陆状态点击文章，秒加载并正确显示阅读次数。

**Comment by aDappDeveloper** [comment]
我这边现在也可以正确加载出阅读量，此Issue可以关掉了。谢谢！
