### ISSUE TITLE
【赞赏】赞赏列表和赞赏总额不正确

### ISSUE THREAD

**Issue by aDappDeveloper** [smart-signature/smart-signature-future#228]
- [x] 单篇文章赞赏总金额数据不对，仅对最后20条数据做了加法。
- [x] 赞赏列表只能显示20条，超出部分无法显示分页。
- [x] 赞赏的时间在手机上和电脑上显示不一致(pc正常，移动端显示比实际时间早8小时)

**Comment by yukiexe** [comment]
@xiaotiandada 這活給你，改成照後端 API 統計

**Comment by xiaotiandada** [comment]
> @xiaotiandada 這活給你，改成照後端 API 統計

收到

**Comment by xiaotiandada** [comment]
fix #238

**Comment by guanchao71** [comment]
1,2,3条在测试环境均已测试通过。
