### ISSUE TITLE
Production is Broken.

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#233]
Professor Ko send an article via Signature through my invitation tonight.
Unfortunately, the production is broken at this moment.

![3491554141554_ pic_hd](https://user-images.githubusercontent.com/2507027/55349957-8234ee00-54ed-11e9-9044-a22ddd40e94b.jpg)

![3501554141568_ pic](https://user-images.githubusercontent.com/2507027/55350093-da6bf000-54ed-11e9-99e4-2b98e67a1e6c.jpg)

I try it by myself and it is also failed.

![3511554141577_ pic_hd](https://user-images.githubusercontent.com/2507027/55350099-ddff7700-54ed-11e9-9b92-1cd423a4450c.jpg)

Please, if you cannot decouple the test and production environment well, please don't do that. This is the first time I see that the production is broken because we need to set up a test environment.

**Comment by cnchenhao** [comment]
已发布
