### ISSUE TITLE
提交功能性bug发布模板

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#235]
============ 使用下方问题反馈模版，进行发文 ============
**操作系统**：Windows / macOS / 安卓 / IOS
**浏览器**：Chrome浏览器/微信浏览器/TP钱包浏览器
**钱包版本**：Scatter插件（版本号）/Scatter桌面（版本号）/TP钱包（版本号）……
**出现环境**：Prod版本/Test环境/本地环境

**描述这个bug**
用一句简洁明了的语言来描述这个bug

**复现流程**
1. 
2. 
3. 

**预期结果**
用一句简洁明了的语言来描述你期望的结果是什么

**问题截图**
如果可能，请尽量插入截图来描述问题

**备注信息**
你可以在此处写下任意备注内容

**Comment by ygllxj2113** [comment]
操作系统：Windows
钱包版本：Scatter插件（版本）
出现环境：Prod版本/
问题是否能复现：可以 

【问题描述1】
  文章页 ipfs :开启BAT平行宇宙
点击赞赏按钮 正确输入评语和赞赏金额    弹窗闪现后提示  赞赏失败   出现闪退现象


![image](https://user-images.githubusercontent.com/47527312/55393464-e7c9be80-556f-11e9-99f5-6701d0160bee.png)


【预期结果】
赞赏成功

**Comment by lychees** [comment]
https://help.github.com/en/articles/creating-issue-templates-for-your-repository

**Comment by guanchao71** [comment]
已经使用了自动化模板来提交bug，无需再手动复制粘贴格式。
#249
