### ISSUE TITLE
打赏与分享相关

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#24]
# 术语统一
- 打赏（tip）、赞助（sponsor）、支持（support）、投资（invest）：转账给作者的行为。
- 分享（share）、复制（copy）：生成与我相关联的分享链接，并将链接分享到社交网站的行为。

# 待做事项
## 打赏
- [x] 从后端拿到 sign_id，写入转账 memo。
- [x] 打赏后，将新生成的 share_id 写入后端。
- [x] 当用户使用分享链接阅读时，打赏时将上游的 share_id 写入转账 memo。
- [x] 二次查验当前 share_id 是否合法。

## 分享
- [x] 在文章頁面加上分享按鈕
- [x] 按下按鈕，生產分享連結
- [x] 根据当前登录的账户，生成形如：`/article/{hash}/?#/invite/{name}` 的链接
- [ ] 跳框選 app 分享
- [ ] <del>把分享連結加鹽</del>

**Comment by yukiexe** [comment]
**關鍵功能** 基本上無論其他地方怎麼改，這些應該都是要有的

**Comment by yukiexe** [comment]
有些更新 #26

**Comment by yukiexe** [comment]
> 按下按鈕，生產分享連結

單純 copy 版已完成
需求更新

-[ ] 按下按鈕，依據 share id 生產分享連結

**Comment by yukiexe** [comment]
你改這一下我還以為被盜帳了，嚇尿

**Comment by yukiexe** [comment]
> 跳框選 app 分享

@floatj @Deasoso 你們會嗎？

**Comment by yukiexe** [comment]
分享還一堆坑，救命

**Comment by floatj** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

這個現在還只能支援特定瀏覽器吧

**Comment by yukiexe** [comment]
@floatj 哇好厲害還找的到

**Comment by yukiexe** [comment]
基本上已完成，合併 issue 避免混亂
