### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#243]
在 Testing

content_script.js:336 Uncaught TypeError: Cannot read property 'then' of undefined
    at Object.check_report (content_script.js:336)
    at Object.init (content_script.js:363)
    at content_script.js:378

**Comment by frankwei98** [comment]
整个项目都没有 `content_script.js` （搜过了），可能是依赖的问题，所以我只能给出判断：
原本要的是一个 `Promise` (Promise 有 `.then` 属性)，但得到了 `undefined`。
希望能有一个重现的步骤，我去试试看？

**Comment by frankwei98** [comment]
刚刚 Google 了一下，content script 好像是和浏览器插件 WebExtension (Chrome / Firefox) 有关 
https://developer.chrome.com/content_scripts
