### ISSUE TITLE
若 Scatter 帐号没有汇入钱包 Owner 权限就无法发文或赞赏，且无报错

### ISSUE THREAD

**Issue by dAAAb** [smart-signature/smart-signature-future#245]
前几天遇到的问题：无法发文、也无法赞赏。
后来发现是我的桌面 Scatter 钱包记录了我先前 Chrome Extension 的资料，但却不是 Owner 权限，只有 Active。所以能签入 https://smartsignature.io 但无法发文和赞赏。
且无法发文没有任何报错，无法赞赏显示的错误讯息是网路错误或余额不足。
希望能有侦测用户 Scatter 登入帐户无 Owner 权限，并显示该问题。帮助 User 除错。感谢喔！

**Comment by lychees** [comment]
This is an intended behavior of Scatter.
<img width="238" alt="屏幕快照 2019-04-02 下午11 13 11" src="https://user-images.githubusercontent.com/2507027/55413960-e95dab80-559c-11e9-9448-da68ffa55110.png">

在 identity 页面会提示你选择 active 还是 owner 权限，
如果 Scatter 中记载的私钥与该权限不符，则会发生上述清空。

解决方法：owner 权限一般不在日常环境中使用，
建议将 Scatter 中的 identity 从 @owner 调整为 @active，之后只需导入 active 权限即可使用。
