### ISSUE TITLE
在智能签名首页增加最多赞赏和最新赞赏列表

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#252]
**开发需求清单**
- [ ] 新增“最多赞赏”排序列表，按照历史赞赏总金额的数量降序排序（最上面是被赞赏最多的）
- [ ] 新增“最新赞赏”排序列表，按照最近获取打赏的顺序降序排序（最上面是最新被打赏的）
**解决方案**

**备选方案**

**备注**

**Comment by yukiexe** [comment]
後端的 api 已出，詳細看 doc

**Comment by frankwei98** [comment]
目前（截至2019年4月3日14点46分）[后端 API 文档](https://github.com/smart-signature/smart-signature-backend/blob/master/doc.md) 只给出了以下功能：
* 按照文章发布时间排行 （一开始就有的功能  ✔）
* 按照**打赏次数**排行 (???)
* 按照打赏金额排行 （对应“按照历史赞赏总金额的数量降序排序” ✔)

那这个 "最新赞赏"功能还要做吗？ @guanchao71

**Comment by guanchao71** [comment]
> * 按照**打赏次数**排行 (???)

暂无此需求。

> 那这个 "最新赞赏"功能还要做吗？ @guanchao71

  @ganjingcun 要做，不知道曹姐有没有提。应该是需要新增后端，给出全服的赞赏信息。

**Comment by guanchao71** [comment]
这是功能需求，pm还没有在测试版中通过测试，请不要关闭issue

**Comment by lychees** [comment]
merge 了关联的 pr 后自动关闭的。
