### ISSUE TITLE
【文章卡片】在文章卡片上增加“赞赏总金额”的数据显示，并且要限制文章卡片上标题的长度

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#253]
## 设计图
![image](https://user-images.githubusercontent.com/10827774/55553393-9ad21d80-5712-11e9-8e11-a28bbda7b710.png)
## 开发需求清单
- [x] 重新设计文章卡片的样式设计
- [ ] 文章卡片上限制标题显示字数为不超过两行
- [ ] 文章卡片上显示信息前端 
    - [x] 文章标题
    - [x] 作者昵称
    - [ ] 赞赏总额
    - [x] 发布时间

## 备注
未来可能需要在卡片上显示“赞赏总次数”“阅读量”信息。

**Comment by yukiexe** [comment]
> 重新设计文章卡片的样式设计

關鍵項，等這個出才開工

**Comment by yukiexe** [comment]
> 限制文章卡片上标题的长度

這個根據環境適配比較好，看看有沒有甚麼現成的插件可用

**Comment by guanchao71** [comment]
后端已经准备完毕：
![image](https://user-images.githubusercontent.com/10827774/55852920-70101b00-5b91-11e9-96c1-8407c9b2af81.png)
