### ISSUE TITLE
【个人主页】个人主页的 layout 改動需求

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#255]
- 资产明细按钮換位置
- 将收益分类显示换成历史总收入
- 新增草稿箱伪按钮并且对所有伪按钮做点击反馈

## 设计图
- 查看个人主页的效果
![主页正常预览效果](https://user-images.githubusercontent.com/10827774/55524808-2ae77700-56c1-11e9-945a-ec8d94bac256.png)

## 开发需求清单
- [x] UI重新设计个人页面的布局设计
- [x] 在个人页面显示收入总和
- [x] 将资产明细入口更换到收入总和旁边
- [x] 增加草稿箱功能伪入口-->#316
- [x] 点击伪按钮之后弹出文字“功能正在开发中”-->#316

**Comment by yukiexe** [comment]
這麼長的標題顯然不合適啊

**Comment by Deasoso** [comment]
开工开工
@guanchao71 以后设计稿到位的时候可以顺便通知一下

**Comment by guanchao71** [comment]
> 這麼長的標題顯然不合適啊，又不是看一眼標題就能開工
> 既然無論如何都要點進來看，那內容在裡頭詳述就好，看過一次就會記得是這篇了
> 
> 你可以練習去掉話中的贅詞

每个issue我都会把概要写在标题中，让第一次看的时候可以大致知道内容是什么。这是为了更好得服务社区开发者和remote开发者。

**Comment by guanchao71** [comment]
> 开工开工
> @guanchao71 以后设计稿到位的时候可以顺便通知一下

approve

**Comment by Deasoso** [comment]
#305 done，草稿箱的Layout也做了，等后端推进

**Comment by Deasoso** [comment]
#311 加了跳转，方便review
