### ISSUE TITLE
【阅读界面】照设计图修界面布局

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#256]
## 设计图
- 阅读界面修改后的样式
![image](https://user-images.githubusercontent.com/10827774/55525134-6df61a00-56c2-11e9-81b9-4a119add11ef.png)

最新修改请参照蓝湖地址：https://lanhuapp.com/url/0sylS 密码:QOMx
## 开发需求清单
- [x] 重新设计文章阅读页面布局设计
- [x] 将原先文章的赞赏列表直接加载显示在文章下方前端 
- [x] 赞赏列表一次加载出来20个
- [x] 向下滚动赞赏列表时，可以连续加载
- [x] 在文章页面显示被赞赏的次数
- [x] 阅读页面底栏位置固定，不随页面滚动。底栏上显示以下信息前端 
    - [x] “分享”按钮
    - [x] “打赏”按钮
    - [x] “裂变系数”的数值
    - [x] “赞赏总额”的数值。

**Comment by yukiexe** [comment]
#293

**Comment by guanchao71** [comment]
This feature basic version released in [v0.1.2](https://github.com/smart-signature/smart-signature-future/releases/tag/v0.1.2).
