### ISSUE TITLE
【赞赏界面】1. 赞赏金额输入框中限制只可输入数字 2. 改评论输入框行高

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#257]
## 开发需求清单
- [x] 赞赏金额输入框正则限制的内容仅为合法的浮点数
- [x] 赞赏评论输入框显示拓展到4行文字高度

**Comment by Deasoso** [comment]
我这边双向绑定失败了，求助。

**Comment by xiaotiandada** [comment]
#337

**Comment by yukiexe** [comment]
> 
> 
> 我这边双向绑定失败了，求助。

我朋友也遇到一樣的問題，神秘

**Comment by guanchao71** [comment]
![image](https://user-images.githubusercontent.com/10827774/55858091-6098ce00-5ba1-11e9-8a63-b653ec16dd73.png)
测试环境通过LGTM
