### ISSUE TITLE
【导航栏】在全局使用统一的导航栏样式

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#259]
## 设计图
![image](https://user-images.githubusercontent.com/10827774/55770347-92813600-5ab6-11e9-9276-4179dac5c26c.png)
最新修改请参照蓝湖地址：https://lanhuapp.com/url/0sylS 密码:QOMx
## 开发需求清单
- [x] 设计导航栏的样式设计
- [ ] 在所有页面的导航栏都采用统一的样式前端 
    - [ ] 导航栏左上角上始终显示返回按钮
    - [ ] 导航栏左上角上始终显示主页按钮

**Comment by lychees** [comment]
Can we close this one now?
