### ISSUE TITLE
API需求

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#261]
**开发需求清单**
- [ ] 通过后端API来获取用户所有收支明细的历史数据（包含文章ID）--P1
- [ ] 通过后端API来获取用户收支明细的数据产生来源（获取对应原文章的hash）--P2
- [x]  通过后端API来获取资产明细的标签（下面四个）--P2
    - [x] 用户的赞赏收益
    - [x] 用户的写作收益
    - [x] 用户的赞赏支出
    - [ ] 用户可提现的金额
- [x] 通过后端API来获取文章的赞赏总数！--P1
- [x] 通过后端API来获取文章被赞赏的总额
- [x] 获得赞赏次数和额度的文章排行榜（order by）
- [ ] 获得/带上token设置用户的昵称
- [ ] 获得/带上token设置用户的头像
- [ ] 带上token将用户的文章标记为已删除
- [x] 获得用户的关注和粉丝列表
- [ ] 带上token将用户的文章内容写入草稿箱
- [ ] 带上token读出用户草稿箱的全部内容

**备注**
API需要先准备好，实际用上不一定在这一期。

**Comment by lychees** [comment]
Please move this issue to backend repo.
