### ISSUE TITLE
scatter.js 中关于 transfer 方法的疑问

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#262]
https://github.com/smart-signature/smart-signature-future/blob/7947b359511b3c4fe2c307eb4e2b3f811fe52d36/src/api/scatter.js#L95-L125

<img width="779" alt="屏幕快照 2019-04-03 上午4 20 08" src="https://user-images.githubusercontent.com/2507027/55433396-dad8b980-55c7-11e9-997d-7421f599237a.png">

为什么上面没有 async 下面有？

**Comment by frankwei98** [comment]
因为 `transferTokenAsync` 里用到了 `await` 
https://github.com/smart-signature/smart-signature-future/blob/7947b359511b3c4fe2c307eb4e2b3f811fe52d36/src/api/scatter.js#L115

而 `transferEOSAsync` 只是单纯返回 `eos().transfer()` (返回类型是 Promise<转账后的交易消息>) ，没用到 `async` `await` (单纯传递返回的 Promise 就好)

**Comment by yukiexe** [comment]
@lychees 你需要學習 Promise, async/await
https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Guide/Using_promises
https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Promise
https://es6.ruanyifeng.com/#docs/async

看完之後呢，再來看我們的api，api們其實都很不標準用法我覺得
