### ISSUE TITLE
【版本号】設置及顯示当前加载版本之版本号供测试及开发人员查詢

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#263]
## 开发需求

- [ ] 需要能查看到当前加载的版本号

## 解决方案
- 在载入界面的时候，在控制台中显示版本号
- 备选：在投资攻略页面的最后加上版本号信息
- 在每次有推送更新的时候，在更新按钮上同步显示更新后的版本号

## 备注
前端开发需要知道自己当前所在的是什么版本。
测试在测试的时候需要知道自己是不是已经是最新版本了。

**Comment by guanchao71** [comment]
#328 很有意思的解决方案by Frank.

**Comment by yukiexe** [comment]
已有
![圖片](https://user-images.githubusercontent.com/3849019/55738768-6041eb00-5a5a-11e9-86d0-d392c9f7e77e.png)
