### ISSUE TITLE
关于保存图片的技术选型

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#264]
**开发需求清单**

- [x] 需要一套可靠的图片存储和读取的flow。

**解决方案**
需要选型一套图片存储的技术方案，是采用自己搭建的图床还是直接上传到ipfs。懂的直接在下面回复。

**备选方案**

**备注**
关联#26

**Comment by ganjingcun** [comment]
就用ipfs

**Comment by guanchao71** [comment]
> 就用ipfs

OK。那在编辑文章的时候插入图片（什么时候开始传到ipfs）上，和预览文章会有影响么？

**Comment by lychees** [comment]
没影响。
