### ISSUE TITLE
【文章列表】首页滚动操作无法加载更多文章列表

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#267]
**描述这个bug**
用户在首页经过某种特定方式浏览文章列表的时候，会触发无法加载更多文章的bug

**复现流程**
1. 进入主页之后向下滚动文章列表到底后
2. 再向上滚动文章列表到头后
3. 下拉刷新文章列表
4. 再次重复步骤1，发现无法加载超过20条内容

**预期结果**
在步骤4 的时候可以正常加载所有文章列表

**Comment by lychees** [comment]
我猜测同样的 bug 是否会在 user page 重现。
（但是测试需要有一个 user 发超过 20 篇文章，请工程师修复代码时留意 double check）

**Comment by yukiexe** [comment]
@xiaotiandada 解掉了嗎？

**Comment by guanchao71** [comment]
close via#350, LGTM
