### ISSUE TITLE
【关注】用户关注操作不能一次成功

### ISSUE THREAD

**Issue by ygllxj2113** [smart-signature/smart-signature-future#268]
**操作系统**：Windows / macOS / 安卓 / IOS
**浏览器**：Chrome浏览器/微信浏览器/TP钱包浏览器
**钱包版本**：Scatter插件（版本号）/Scatter桌面（版本号）/TP钱包（版本号）……
**出现环境**：所有环境

**描述这个bug**
可以点击多次关注  或取消关注的状态  实际是用户已不处于登录状态导致 用户登录状态停留时间可能与不同钱包的解锁状态停留时间影响  这个地方可以引入一个判断或提示

**复现流程**
1. 用户长时间不操作或退出登录
2. 进入他人主页点击 关注  或  取消关注
3. 可以多次点击  不返回正确结果  不提示原因

**预期结果**
返回预期操作结果或正确提示原因

**Comment by Deasoso** [comment]
fixed #271

**Comment by AkemiKusane** [comment]
#284  测一下？通了就关了

**Comment by lychees** [comment]
It seems that it does not work.
连正常的关注的不可以了。
