### ISSUE TITLE
測服的文章列表

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#272]
**描述这个bug**
為什麼有時候會加載正服的？

**Comment by frankwei98** [comment]
我这边在 https://sign-dev.dravatar.xyz/ 无法重现这个问题。

如果问题还存在，请开启浏览器的开发者工具，打开 `Network` 选项卡并录制视频还原过程

谢谢合作 :)

**Comment by yukiexe** [comment]
![圖片](https://user-images.githubusercontent.com/3849019/55487176-29399700-5660-11e9-8cba-e9a96fc7acee.png)
![圖片](https://user-images.githubusercontent.com/3849019/55487205-39ea0d00-5660-11e9-8cd6-4b14c9457a64.png)

**Comment by yukiexe** [comment]
![圖片](https://user-images.githubusercontent.com/3849019/55487262-5ede8000-5660-11e9-9688-a004ecd05a37.png)

**Comment by yukiexe** [comment]
![圖片](https://user-images.githubusercontent.com/3849019/55487414-a1a05800-5660-11e9-8de8-09fd1a2c65e4.png)

**Comment by frankwei98** [comment]
谢谢，看到了照片，确实是生产环境的内容。

不过自从上次小田改了 npm scripts 之后， 
https://sign-dev.dravatar.xyz/ 现在都是以 `development` 编译

https://github.com/smart-signature/smart-signature-future/blob/5c903eca51c031d6f75a22d9b1d1974a9199a1e9/package.json#L10

https://github.com/smart-signature/smart-signature-future/blob/5c903eca51c031d6f75a22d9b1d1974a9199a1e9/package.json#L7

按照 `registerServiceWorker.js` 的逻辑，`development` mode应该不存在 service worker 才对。


https://github.com/smart-signature/smart-signature-future/blob/5c903eca51c031d6f75a22d9b1d1974a9199a1e9/src/registerServiceWorker.js#L9-L37



![image](https://user-images.githubusercontent.com/3261732/55489063-d06bfd80-5663-11e9-862f-6e12d1ae6341.png)

我这里在影子模式下测试了 https://sign-dev.dravatar.xyz/ 和 https://www.smartsignature.io/ 没有发现上述问题

我个人的判断：不排除是浏览器缓存问题，老的版本就是读生产环境的API
