### ISSUE TITLE
Netlify 設定修正

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#283]
**出现环境**：Test环境

**描述这个bug**
Netlify 目前在 Testing 有兩套，而且每次都失敗，需要修正

**Comment by frankwei98** [comment]
另外一个不是我setup的
我也不知道是谁setup的
我也不能关掉另外一个（因为不是我setup的）
我最多关掉整个netlify 对 repo 的 access
这样可以不？

咚咚 <notifications@github.com>于2019年4月3日 周三下午10:25写道：

**Comment by frankwei98** [comment]
找到了，是 @cnchenhao 
![image](https://user-images.githubusercontent.com/3261732/55490065-b16e6b00-5665-11e9-9c6a-7cdf3d7a02b8.png)

![image](https://user-images.githubusercontent.com/3261732/55490124-ce0aa300-5665-11e9-9e22-1f14db87022f.png)

问题出在这儿：
![image](https://user-images.githubusercontent.com/3261732/55490156-dd89ec00-5665-11e9-811c-f45d2ef5f657.png)

修正 build 命令为 `npm run build` 谢谢

**Comment by yukiexe** [comment]
> 
> 
> 找到了，是 @cnchenhao
> ![image](https://user-images.githubusercontent.com/3261732/55490065-b16e6b00-5665-11e9-9c6a-7cdf3d7a02b8.png)
> 
> ![image](https://user-images.githubusercontent.com/3261732/55490124-ce0aa300-5665-11e9-9e22-1f14db87022f.png)
> 
> 问题出在这儿：
> ![image](https://user-images.githubusercontent.com/3261732/55490156-dd89ec00-5665-11e9-811c-f45d2ef5f657.png)
> 
> 修正 build 命令为 `npm run build` 谢谢

感謝你找到是誰，終於(感動)

**Comment by cnchenhao** [comment]
已处理
