### ISSUE TITLE
【代码规范】Make Code Readability Great Again 智能签名迷惑行为大赏

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#288]
- [ ] username 与 currentUsername ![5941554318659_ pic](https://user-images.githubusercontent.com/2507027/55508592-cdd1ce00-568c-11e9-8a11-2a8b3a9a7a2a.jpg)

- [ ] ArticlesRanking 与 ArticlesRankings ![5831554318232_ pic](https://user-images.githubusercontent.com/2507027/55508517-a975f180-568c-11e9-96ea-017af48acc51.jpg)

**Comment by yukiexe** [comment]
還一堆名字命名上還有相同功能的 func 散落各地的問題。
嗯....有些人案情嚴重，有些人偶而犯之，不好點名。
我救火是蠻累的。

**Comment by Deasoso** [comment]
#303

**Comment by yukiexe** [comment]
Great Again 梗已經用過了，換一個
