### ISSUE TITLE
【赞赏按钮】未登录情况下进入已打赏过的文章页面，点击打赏按钮后状态不会自动变为已打赏

### ISSUE THREAD

**Issue by AkemiKusane** [smart-signature/smart-signature-future#298]
RT
用户背景是实际上用户已经打赏过这篇文章，但是当前还没有登录
因为你点击赞赏按钮之后会唤起登录
登录之后正常情况是会检测到用户已经赞赏过，所以按钮需要自动转换为不可点击的已赞赏状态

**Comment by guanchao71** [comment]
## 补充另一个问题：
登录情况下对一篇我已经打赏过的文章重复打赏异常提示显示的却是余额不足。
如果成功解决本issue则无需处理该情况。否则使用备用方案：
## 备用方案
检测到用户重复打赏之后，弹出“请勿重复赞赏”的异常提示消息

**Comment by Deasoso** [comment]
fixed #360

**Comment by guanchao71** [comment]
> fixed #360

测试环境没有测出问题。
Nice work!终于解决了这个问题。[干杯！]
