### ISSUE TITLE
【文章页适配】[iphoneX] 在浏览文章页面底栏部分被遮挡 -> 针对性适配

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#299]
![image](https://user-images.githubusercontent.com/10827774/55548242-a1a66380-5705-11e9-9781-8770fb42a5cb.png)

## 开发需求清单
- [ ] 适配iphoneX以上的苹果手机

## 解决方案
在iphoneX手机上将底栏增高一段空白

**备注**

**Comment by lychees** [comment]
有截图么

**Comment by xiaotiandada** [comment]
#314

**Comment by guanchao71** [comment]
测试环境通过
