### ISSUE TITLE
添加文章的模块开发

### ISSUE THREAD

**Issue by frankwei98** [smart-signature/smart-signature-future#3]
以下是（应该）要实现的功能？
- [x] 开辟页面路由
- [x] 移植编辑器
- [x] 文章发送到 IPFS

**Comment by yukiexe** [comment]
> 开辟页面路由
甚麼意思

**Comment by yukiexe** [comment]
> 移植编辑器

我搬一個最右的(好像是markdown)，有三個

**Comment by frankwei98** [comment]
@yukiexe 在 router.js 新加一个 route 给编辑组件

——-

markdown editor sounds good to me

**Comment by yukiexe** [comment]
#15

**Comment by frankwei98** [comment]
Done in #21, closing this
