### ISSUE TITLE
【赞赏列表】在测试环境下的一篇文章下面出现了同一个用户的两次连续打赏记录

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#300]
**出现环境**：Test环境

**描述这个bug**
在测试环境下的一篇文章下面出现了同一个用户的两次连续打赏记录
https://sign-dev.dravatar.xyz/article/QmWiQHavJLr5sa9SoApDYFpBgMfLDkBoUdEUyAVyF72Swy

**预期结果**
每个用户对同一篇文章只能打赏一次，不会出现同一个用户对同一篇文章打赏两次

**问题截图**
![image](https://user-images.githubusercontent.com/10827774/55548242-a1a66380-5705-11e9-9781-8770fb42a5cb.png)

**备注信息**

**Comment by xiaotiandada** [comment]
fix #301

**Comment by yukiexe** [comment]
原來是個顯示問題，嚇死人
