### ISSUE TITLE
【昵称设置】在个人页面中设置昵称

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#308]
## 设计图
- 编辑中的个人信息栏效果
![编辑中的效果](https://user-images.githubusercontent.com/10827774/55524911-7c900180-56c1-11e9-84f6-56faf8bfe98a.png)
## 开发需求清单
- [x] 点击编辑按钮可以开始设置昵称
- [x] 进入编辑状态后用户昵称处显示为输入框，并且默认填写用户的EOS ID或者上一个昵称
- [x] 点击保存之后验证昵称是否是全平台唯一的
     - [x] 如果不是唯一的昵称则提示“昵称已存在，请重新设置”
     - [x] 如果是唯一的昵称则提示“保存成功”

## 备注
用户的昵称需要保证唯一性

**Comment by Deasoso** [comment]
#338

**Comment by guanchao71** [comment]
4月10号晚上，我在测试环境设置了昵称，使用Ctrl+f5刷新页面可以显示出我的昵称。
4月11号凌晨再次打开测试环境，发现我的昵称又消失了，需要进一步测试验证。

**Comment by guanchao71** [comment]
![image](https://user-images.githubusercontent.com/10827774/55908703-b8205380-5c0c-11e9-81cb-2f984bade06f.png)
在PC浏览器上查看出来的排版是错位了的。

**Comment by Deasoso** [comment]
> ## 问题说明
> 4月10号晚上，我在测试环境设置了昵称，使用Ctrl+f5刷新页面可以显示出我的昵称。
> 4月11号凌晨再次打开测试环境，发现我的昵称又消失了，需要进一步测试验证。
> 
> ## 复现流程
> 1.点击编辑按钮
> 2.输入昵称
> 3.点击完成
> 
> ## 截图信息
> ![image](https://user-images.githubusercontent.com/10827774/55908872-22d18f00-5c0d-11e9-87f5-6fd596e78178.png)
> ![image](https://user-images.githubusercontent.com/10827774/55908893-30871480-5c0d-11e9-8da7-077a7239adf9.png)

错误未复现……

**Comment by Deasoso** [comment]
> ![image](https://user-images.githubusercontent.com/10827774/55908703-b8205380-5c0c-11e9-81cb-2f984bade06f.png)
> 在PC浏览器上查看出来的排版是错位了的。但是点击编辑按钮后，又会变成正常的样式。

#356

**Comment by guanchao71** [comment]
Good work！
