### ISSUE TITLE
【favicon】替换prod的favicon

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#310]
## 参考图片
这是当前的页标签样式
![image](https://user-images.githubusercontent.com/10827774/55695561-b592e380-59eb-11e9-9e31-f1c3d020c291.png)
## 预期结果
将这个logo给转换成favicon替换上去
![智能签名logo](https://user-images.githubusercontent.com/10827774/55695571-c3e0ff80-59eb-11e9-981a-82ca0437f944.png)

**Comment by Deasoso** [comment]
#313

**Comment by guanchao71** [comment]
![image](https://user-images.githubusercontent.com/10827774/55698267-a154e380-59f7-11e9-81a4-1e9747d1da6d.png)
测试环境已通过。
