### ISSUE TITLE
【重编辑】重新编辑已经发布过的文章

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#317]
## 需求说明
文章拥有者需要在文章页面中选择对文章进行重编辑后，SS从后端获取文章原始内容，并填充在编辑页面中。当用户选择保存修改后的内容时请求用户签名。通过签名之后将新的内容上传到IPFS，并将数据库中的记录下新的文章hash地址（保留原hash）。以达到重新编辑的效果，并且可以保留历史记录。

## 参考图
![image](https://user-images.githubusercontent.com/10827774/56107959-ac6dbd80-5f7b-11e9-859b-59ace8ef65fb.png)

## 开发需求清单
- [x] 按照设计稿的样式放置按钮，并且配色参考设计稿的样式
- [x] 作者在登录的情况下，在文章页面中自动添加“重编辑”按钮的显示
- [x] 点击“重编辑”按钮后从后端获取文章标题和正文信息，将正文信息自动填充到“重编辑页面”中
     - [x] 在“重编辑页面”中点击返回后，原文不做任何变动
     - [x] 在“重编辑页面”中点击保存后，请求用户签名
- [x] 确认保存重编辑内容3秒后跳到修改后的文章页面

## 备注
删除和重编辑按钮收纳在一个抽屉菜单中

**Comment by lychees** [comment]
This is an important milestone for our UX. Big impact!

**Comment by guanchao71** [comment]
完成得非常好！Well Done！
