### ISSUE TITLE
【裂变系数】在编辑页面增加裂变系数设置

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#319]
## 需求说明
#157 已过期。
需要在用户编辑未发布文章的界面中，增加裂变系数设置的功能。
当前设计为滑动条：让用户在有限的范围内滑动到合适的位置，不需要处理输入溢出的问题。

## 设计图
滑动条就放置在当前裂变系数输入框的位置，选中的数值显示在滑动条左侧。
![image](https://user-images.githubusercontent.com/10827774/55967918-acd13480-5cad-11e9-8b91-d8518d358c42.png)

## 功能清单
- [x] 按照设计图示的示意制作滑动条来控制输出的裂变系数数值
- [x] 滑动条输出的裂变系数范围限制为：1.0~5.0
- [x] 若用户不做改动，裂变系数则默认为2.0的位置
- [x] 滑动控制杆的时候，裂变系数显示会动态变化

**Comment by lychees** [comment]
https://github.com/smart-signature/smart-signature-EOS-contract/blob/48ca1c95737c55a595dea7d8046686dd0198f4d6/beta-version/signature.bp/signature.bp.cpp#L41

看了一下合约现在是 1-2。
合约现在没人改，建议和合约对齐。
