### ISSUE TITLE
【代码规范】把這些影分身處理掉

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#325]
**开发需求清单**
- [x] 整頓 code
https://github.com/smart-signature/smart-signature-future/blob/48435f565c864ca001cb09c8967807b8fa3e6228/src/views/Publish.vue#L134

- [x] 去除 authDemo 
https://github.com/smart-signature/smart-signature-future/blob/48435f565c864ca001cb09c8967807b8fa3e6228/src/views/User/index.vue#L137

現在統一在發送後端請求前會有處理 access token 的步驟，如有特殊需求，可以另行使用 backend.js 中的 getAuth()

**Comment by yukiexe** [comment]
authDemo 給 @Deasoso 清理。
API.getSignature 給 @xiaotiandada 看怎麼包裝起來比較好，裸叫 API.getSignature 不好，這關係到用戶體驗流程，必須搬遷包裝到其他地方。

**Comment by Deasoso** [comment]
#356

**Comment by yukiexe** [comment]
#359

**Comment by yukiexe** [comment]
#375 整頓 code
