### ISSUE TITLE
【多鍊支持】 ETH 篇

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#326]
**开发需求清单**
引入 ETH 帳號可以登錄的功能
仿照 scatter.js, store.js 引入設計登錄需要的 func ，並能記錄在 store
不必合併到目前的登錄系統中，先寫完功能之後在考慮整體如何設計帳號合併

**Comment by lychees** [comment]
注意 ETH 的版本我们暂时不写合约，参考 ONT 的方法进行实作就好。
（可能需要学习 Vyper？不如找更熟悉的人写？）

**Comment by yukiexe** [comment]
都不寫合約，合約的邏輯要移往後端了

**Comment by yukiexe** [comment]
總不能本體一份合約EOS一份ETH一份吧 233

**Comment by lychees** [comment]
没人做，close for now.

**Comment by yukiexe** [comment]
交付給 frank 了不是嗎?

**Comment by frankwei98** [comment]
抱歉。最近学业有点忙，各种任务堆在我头上。
因为 ETH (MetaMask) 用户不多，我也没怎么放心上，

如果着急上线可以 assign 给别人，如果不急我可以做。
就是登录部分有点麻烦，因为要对付 Replay Attack，应该要前端与后端协商一个 nonce

现在开了个新 branch https://github.com/smart-signature/smart-signature-future/commits/support-web3

**Comment by yukiexe** [comment]
好的，辛苦了
