### ISSUE TITLE
【用户界面】历史总收入 is wrong。

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#339]
<img width="448" alt="屏幕快照 2019-04-10 上午5 18 17" src="https://user-images.githubusercontent.com/2507027/55836110-32d76900-5b50-11e9-8d66-0f55b85225ed.png">

**Comment by Deasoso** [comment]
https://github.com/smart-signature/smart-signature-future/blob/473a03e63af571d8ff5974a2c141cf8998696d62/src/views/User/index.vue#L50

我的我的，没注意这俩不是变量是方法，你顺手改了吧，我这没收入不便测试

**Comment by lychees** [comment]
请使用后端接口统计历史收入，不要在前端遍历。
https://github.com/smart-signature/smart-signature-backend/commit/65021221838336bfcee63c7e10f434ce784dc662

**Comment by guanchao71** [comment]
这里的历史总收入经过测试实际上显示的是“待提现余额”的数值。

**Comment by lychees** [comment]
https://github.com/smart-signature/smart-signature-future/pull/364
