### ISSUE TITLE
【提案】 加入對 pocket 的支持

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#342]
### 介紹功能： ###
https://getpocket.com/  

## 理由 ##
1. 好用，至少我很愛用。效果比書籤收藏文章好的多 (個人經驗：月瀏覽頁面量 6k，書籤收藏量 1k)
2. 沒被牆
3. 主流 sns 或內容網站都有支援
4. 給用戶一個收藏文章的方法而我們不必自己開發
5. 原生支援多平台開啟其列表
6. 開發簡便，只需加一個按鈕 https://getpocket.com/publisher/button
7. 進階好處：用戶用自己的 pocket 收藏了，數量級夠多，能被 pocket 在其推薦中被刷出來，增加流量入口
8. 進階好處：文章作者用 pocket 可以收藏自己的文章做成一個 list 快速分享，這 list 可以包含其在其他網站上的文章 (跟平台簽協議，禁止轉載的類型等原因無法搬移過來。其他不是作者但是想列於 list 的相關文章) 而不必局限於 ss
9. 我們自己做收藏功能實在是效益低的一個做法，還得登錄去查看，也不支援其他網站。個人除了內容量夠大像是 b站、知乎的收藏功能會使用外，其他都用 pocket 或書籤收藏。

**Comment by yukiexe** [comment]
請 @guanchao71 @AkemiKusane 兩位表達意見

**Comment by guanchao71** [comment]
先占个位置：
我的基本观点：本来就没有打算做内建收藏夹的功能。因为赞赏本身就是收藏机制。

**Comment by lychees** [comment]
这是一个好东西，我也用。智能签名原本的设计就不会做成面面俱到，而只关注金流，
我觉得要专门做一期 roadmap 研究对各种第三方支持。（最重要的我认为是 medium 的插件）

**Comment by yukiexe** [comment]
> 专门做一期 roadmap 研究对各种第三方支持

交給你了 xD

加入這個真的只要一行，你們到底讓不讓我加 xDD

**Comment by lychees** [comment]
只要一行当然可以先加（我以为要 100 行）。

**Comment by yukiexe** [comment]
done /w #381

**Comment by lychees** [comment]
Good work.
