### ISSUE TITLE
【讚賞功能】去除幻影

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#343]
**开发需求清单**
關於 "// 手动添加一个赞赏"
不要直接加一個沒有被後端確定已儲存的幻影，容易誤導開發人員或是使用者

**解决方案**
改成拿 sendComment 的回傳值去添加，請跟 @ganjingcun 協調回傳值設計

**Comment by yukiexe** [comment]
媽呀，誰寫的？

![圖片](https://user-images.githubusercontent.com/3849019/55922967-131a7080-5c36-11e9-98b6-cd81bafb1c22.png)

你看文檔，看有甚麼不一樣？
https://get-scatter.com/docs/api-request-arbitrary-signature

**Comment by guanchao71** [comment]
如果引入CPD重复代码检测工具来对完全一致copy过来的代码进行检查，会对这种状况有改善？

**Comment by yukiexe** [comment]
開頭的那項是個流程 bug
第二個是個未完成品
引入應該是沒法解決這問題

**Comment by xiaotiandada** [comment]
> **开发需求清单**
> 關於 "// 手动添加一个赞赏"
> 不要直接加一個沒有被後端確定已儲存的幻影，容易誤導開發人員或是使用者
> 
> **解决方案**
> 改成拿 sendComment 的回傳值去添加，請跟 @ganjingcun 協調回傳值設計

已fix
