### ISSUE TITLE
【赞赏按钮】赞赏按钮状态不正常

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#346]
**操作系统**：Windows
**浏览器**：Chrome
**钱包版本**：Scatter插件
**出现环境**：本地环境

**描述这个bug**
在已經確定自動登錄生效的情況下，赞赏按钮状态還是沒有變成已讚賞

**需求**
需要調整赞赏状态變化的偵測方式或設定其狀態的值的時間點

**Comment by yukiexe** [comment]
順帶一提，之前有人提到已讚賞後又能按讚賞，最後在合約端被擋下跳錯誤訊息也是這個失效導致沒能攔截二次讚賞的情況造成的

**Comment by yukiexe** [comment]
由於實際上還有多關卡防止二次讚賞情況發生，這個優先級可以低一點

**Comment by guanchao71** [comment]
#298 应该和这个重复的吧
