### ISSUE TITLE
【赞赏后】成功赞赏之后界面上只会显示我自己的赞赏信息

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#349]
## 描述这个 bug
在我赞赏完成之后，页面就只会剩下我自己的赞赏信息。需要刷新页面才可以全部显示出来

## 复现流程
1. 进入文章页
2. 点击赞赏并且成功赞赏-->问题
3. 刷新页面-->解决方案

## 预期结果
在用户赞赏完成之后，保留原有赞赏队列，在队列顶端增加我的赞赏信息。

## 备注信息
虽然下拉刷新一下就可以解决，但确实是一个 bug 呢。

**Comment by xiaotiandada** [comment]
#267

**Comment by guanchao71** [comment]
> #267

LGTM，well done !
