### ISSUE TITLE
【CI】CI is Broken

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#351]
<img width="492" alt="屏幕快照 2019-04-10 下午7 18 08" src="https://user-images.githubusercontent.com/2507027/55875524-dadc4900-5bc7-11e9-886c-f16fe9eba4d3.png">

Let's fix it!

**Comment by AkemiKusane** [comment]
#352

**Comment by yukiexe** [comment]
看起來打勾綠色了所以是 work 了
