### ISSUE TITLE
【收益数据】换用从后端接口来获取收益历史数据

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#355]
## 问题描述
没有使用后端提供的API接口作为历史数据的来源，而是从前端遍历了所有的明细后做了数值运算。

## 需求和预期
- [ ] 请使用后端提供的数据API作为“赞赏历史收益”“创作历史收益”的数据来源

## 备注反思
by @yukiexe 
1. 前端因為後端沒出 api ，前端硬出了抓鍊上資料的作法
2. 在第一波 realease 的同天，後端開始出了 api
3. 接著後端持續出 api ，前端修 bug ，產品改設計和 UI
4. 前端照產品加上新設計和照後端新出的 api 加上
5. 取簽名，即 acess token 事件，還有一票的功能微調(調樣式還真的需要時間)
6. 後端持續出 api ，前端陸續加上
7. 出現剛剛討論的漏改
我覺得會出現這種事情很合理，真的不太是誰的錯。
中間還有遷移分離生產/測試的環節，前端後端合約全都要一整套弄

**Comment by lychees** [comment]
See also: https://github.com/smart-signature/smart-signature-future/issues/339.

**Comment by lychees** [comment]
https://github.com/smart-signature/smart-signature-future/pull/364
