### ISSUE TITLE
【提案】加入授權表明

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#377]
**提案說明**
加入這種東西

![圖片](https://user-images.githubusercontent.com/3849019/56036726-275a8c80-5d60-11e9-84c1-41b5bf1a9e01.png)

**實現方案**
初步方案給作者 1個選項可以勾選 "未经作者授权，禁止转载" 表明授權狀態
UI -> 發布文章頁找個地方放
前端 -> 勾選框，送到後端的參數加一個
後端 -> 表加一項，調用文章數據的時候多傳一個參數
前端 -> 顯示文章的地方照多加一行

進階... 看看作者們需不需要，他們是可以在文章末自己加上的

**Comment by lychees** [comment]
加加加，
但我觉得优先级没有绑定社交账号高（XD
