### ISSUE TITLE
【关注/粉丝】列表中的幽灵用户。

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#384]
一图流。

<img width="393" alt="屏幕快照 2019-04-14 下午4 22 39" src="https://user-images.githubusercontent.com/2507027/56090211-c05ce500-5ed1-11e9-85dc-2fea2411bc40.png">

点击后会进入未知领域。

<img width="862" alt="屏幕快照 2019-04-14 下午4 24 45" src="https://user-images.githubusercontent.com/2507027/56090218-d8ccff80-5ed1-11e9-82b0-a9bb6b3bd04d.png">

**Comment by Deasoso** [comment]
我只是如实显示后端数据，可能需要后端访问数据库将其手动删除。

**Comment by Deasoso** [comment]
初步fix,#385 已经实现将幽灵用户隐藏
不过从根本解决问题可能还是需要删除数据库数据。

**Comment by AkemiKusane** [comment]
似乎还存在粉丝数量和粉丝列表中的粉丝数量不正确的问题？
不一定对，有的是正确的有的就会多一两个/少一两个

**Comment by Deasoso** [comment]
> 似乎还存在粉丝数量和粉丝列表中的粉丝数量不正确的问题？
> 不一定对，有的是正确的有的就会多一两个/少一两个

对对，似乎是错误地将幽灵用户计入了。
那没办法了，让后端同学去解决吧。

**Comment by lychees** [comment]
> 初步fix,#385 已经实现将幽灵用户隐藏
> 不过从根本解决问题可能还是需要删除数据库数据。

不建议掩耳盗铃。

**Comment by ganjingcun** [comment]
是之前测试接口留下的脏数据，包括随意的用户名和空字符串，已经从数据库删去。前端不用做什么。恢复吧。

**Comment by Deasoso** [comment]
> 是之前测试接口留下的脏数据，包括随意的用户名和空字符串，已经从数据库删去。前端不用做什么。恢复吧。

前端无需修改，只是过滤掉空用户名，就这样吧。
