### ISSUE TITLE
【Avatar】getAvatarImage 沒有過濾空 hash 而仍然送請求

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#387]
**出现环境**：Test环境/本地环境

**描述这个bug**
Request URL: https://apitest.smartsignature.io/image/
Request Method: GET
Status Code: 400 
Remote Address: 127.0.0.1:1080
Referrer Policy: no-referrer-when-downgrade

invalid ipfs path: path must contain at least one component

**Comment by yukiexe** [comment]
@AkemiKusane 指派給人修後換 Assignees

**Comment by xiaotiandada** [comment]
这个我修了 avatar 未空的时候直接返回默认Logo

**Comment by lychees** [comment]
IMHO，这个已经被 fix 了。
