### ISSUE TITLE
【阅读次数】统计设计不合理

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#392]
## 描述 
- 只有从首页进入文章才会 +1，直接通过链接或原地刷新访问文章不会 +1
- 进入文章后的 +1，要下一次浏览时才会显示

所以假设当前文章阅读数时 0，从主页进入访问后，阅读数还是 0，原地刷新后阅读数变成 1，
再次原地刷新后还是 1

## 预期
所以假设当前文章阅读数时 0，从主页进入访问后，阅读数是 1，原地刷新后阅读数变成 2，
再次原地刷新是 3

**Comment by yukiexe** [comment]
環境是？

**Comment by yukiexe** [comment]
你們討論的真是好笑，明明是因為 bug 整個功能都不 work 了

![圖片](https://user-images.githubusercontent.com/3849019/56177311-c1f0ef00-6030-11e9-9cce-f71db11f5042.png)

https://github.com/smart-signature/smart-signature-future/blob/1c0bafe9b2526884213eb84ed862cd8b3707fd8c/src/api/backend.js#L144-L146

在 currentAccount() 為 null 的時候整個炸了，導致 callback 沒執行，也就沒送出請求到後端增加計數

新版已修
https://github.com/smart-signature/smart-signature-future/blob/3ee6493db08425ce334378a003327c28e39759d3/src/api/backend.js#L130-L133

**Comment by lychees** [comment]
测试服 work
