### ISSUE TITLE
【社交媒体】增加Telegram群组的入口

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#393]
根据以往的经验，这次我们就先不弄其他 media 了
需要 UI 设计这个放在哪里
[t.me/smartsignature_io](t.me/smartsignature_io)

**Comment by guanchao71** [comment]
由于我们的主页是滚动加载列表的，因此建议在“投资攻略”按钮旁边加入“进TG讨论”的入口。
![image](https://user-images.githubusercontent.com/10827774/56185028-cdeba980-604e-11e9-8ed9-8c195a56800c.png)

**Comment by xiaotiandada** [comment]
![image](https://user-images.githubusercontent.com/24250627/56273606-a1f42500-612f-11e9-807a-5e3d9e86a005.png)
