### ISSUE TITLE
【社交分享】Facebook、Twitter 上的 Preview

### ISSUE THREAD

**Issue by aDappDeveloper** [smart-signature/smart-signature-future#397]
**在 Facebook 或 Twitter 上分享某篇文章，可以自动加载出文章图片及题目**

**解决方案**
优化前端代码结构，使之通过以下三个测试

Google Structure Data Tool - 更方便其他社交媒体抓取结构数据：
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fsmartsignature.io 

FB 分享链接检测：
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fsmartsignature.io%2Farticle%2FQmRoUwGkwGLwwUnUQHnHptHnvzZ16LiuW6aR5YwP834GJD

可从该网页查看文章在 Twitter 分享的预览
https://cards-dev.twitter.com/validator

**备注**
如需文案配合，请找 AA 。

**Comment by yukiexe** [comment]
大概要用這個
https://ssr.vuejs.org/zh/

**Comment by guanchao71** [comment]
已转移
issues/25
