### ISSUE TITLE
【关注和粉丝】我的关注列表和粉丝列表信息错误！

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#399]
## 出现环境
Test环境
## 描述这个bug
我的入口处显示我有5个粉丝，但是点进去后实际却显示了超过5个粉丝的信息。
## 复现流程
1. 先记录自己的关注数量
2. 去关注一个用户，然后查看自己的关注数量
3. 再取消关注这个用户，然后查看自己的关注数量
4. 然后再去查看自己的关注列表

## 预期结果
在我取消关注的时候，从我的关注列表中也一并删除这个用户的信息显示

## 问题截图
![image](https://user-images.githubusercontent.com/10827774/56231216-7ed66080-60b0-11e9-8875-c6447875b886.png)
![image](https://user-images.githubusercontent.com/10827774/56231229-8c8be600-60b0-11e9-9d75-5706227e96fa.png)

## 备注信息
在用户取消关注的时候，实际上并没有删除这段关系，而仅仅是前端的数值和关注按钮获取了正确的状态。自己可以试验一下：先关注一个用户，然后再取消关注，但是在我的关注列表里面还是可以看到这个用户。

**Comment by Deasoso** [comment]
经测试，问题已经修复。
