### ISSUE TITLE
[推進中] 文章模块

### ISSUE THREAD

**Issue by frankwei98** [smart-signature/smart-signature-future#4]
- [x] 尽量向设计稿靠拢
- [x] Share + 打赏 功能
- [x] PC / 移动端不同 layout （可选） => [未來版本]

**Comment by yukiexe** [comment]
from #45 
- [ ] **能够正确显示文章基础信息**
    - [x] 文章标题
    - [ ] 作者用户名
    - [x] 发布日期
    - [ ] 阅读量
    - [ ] 打赏人次
    - [ ] 总打赏金额
    - [ ] 裂变系数
- [ ] **能够正确显示正文**
    - [ ] 能够正确渲染正文格式信息
    - [ ] 能够正常加载用户上传的图片
    - [ ] 能够支持显示用户插入的图床图片
- [ ] **能够正确的实现打赏功能**
- [ ] 打赏的时候可以附加留言
- [ ] **能够正确实现分享功能**
    - [ ] 没有打赏时候分享链接
    - [ ] 已经打赏时候分享链接
- [ ] **点击总打赏的金额可以跳转到打赏队列页面**
- [ ] **点击用户名可以跳转到他人主页**

**Comment by yukiexe** [comment]
#90

**Comment by yukiexe** [comment]
- 裂变系数
#93

**Comment by yukiexe** [comment]
> [隱藏] 阅读量

移動到 #51

**Comment by yukiexe** [comment]
Footer 那五個簡直是四天王

**Comment by guanchao71** [comment]
> Footer 那五個簡直是四天王

foot需要按照设计稿雕刻出来，在不同尺寸机型上实验一下使用的效果。then，我们可以考虑改掉foot的固定位置属性。

**Comment by yukiexe** [comment]
没有打赏 / 已经打赏 #102

**Comment by yukiexe** [comment]
> 在不同尺寸机型上实验一下使用的效果

目前在 css 上的設定是他是一塊東西，然後用 http://v1.iviewui.com/components/grid
去設定的，所以應該如何都不會跑得太歪。

並沒有強制設定在哪個座標之類的

**Comment by yukiexe** [comment]
這個 tag 以後可以用，記錄下
http://v1.iviewui.com/components/tag

**Comment by yukiexe** [comment]
> 打赏的时候可以附加留言 

#111
但是理所當然沒有寫入後端，哈哈哈
後端還沒出 API

**Comment by yukiexe** [comment]
來做 **总打赏金额**

**Comment by yukiexe** [comment]
剩 #59 #97 ，先行 close 減少混亂
