### ISSUE TITLE
【用户体验】关注信息页面中，将关注和粉丝标签页位置对调

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#400]
## 任务说明
因为我们设计师的失误，导致粉丝列表和用户列表入口的位置和页面中摆放位置是交错对应的。
经过调研了传统互联网产品（微博、微信读书），发现凡是关注都在左边，粉丝在右边，所以入口的摆放样式延用不变，修改内页的标签页排列方式。

## 需求说明

- [ ] 将内页的“粉丝”“关注”标签页位置对调

## 截图
![image](https://user-images.githubusercontent.com/10827774/56231567-5dc23f80-60b1-11e9-88b6-abde4588dac0.png)
![image](https://user-images.githubusercontent.com/10827774/56231587-6adf2e80-60b1-11e9-9fb4-890fd643bb60.png)

## 备注
下次遇到这种明显看起来有问题的状况，先和PM沟通。相信自己的判断。

**Comment by lychees** [comment]
https://github.com/smart-signature/smart-signature-future/pull/410
