### ISSUE TITLE
【文章显示】加粗内容显示BUG

### ISSUE THREAD

**Issue by qgpcybs** [smart-signature/smart-signature-future#401]
**操作系统**：安卓
**浏览器**：微信浏览器
**钱包版本**：Scatter插件
**出现环境**：Prod版本

**描述这个bug**
通过微信打开文章，部分加粗文字未显示加粗，且PC端chrome打开无此问题

**复现流程**
1. 文章例如：https://smartsignature.io/article/353?invite=bagawuziwei1
2. 用PC的chrome和微信分别打开
3. 最下方例如“创作工具”等加粗内容显示不同

**Comment by yukiexe** [comment]
微信會改別人的 css 顯示，不管寫了甚麼被他蓋了就沒解了
@AkemiKusane 你之前是這樣說的？

**Comment by AkemiKusane** [comment]
如果他要做，很容易就可以做到。
但是这个问题你目前还没办法确定是微信还是浏览器的问题。
需要测一下。

**Comment by guanchao71** [comment]
已转移
issues/51
