### ISSUE TITLE
【用户体验】提现余额转支付

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#402]
<img width="438" alt="屏幕快照 2019-04-17 上午11 10 28" src="https://user-images.githubusercontent.com/2507027/56258262-7eb28100-6101-11e9-982d-f35091f3008d.png">

**Comment by guanchao71** [comment]
## 需求分析
我分析这个需求：用户其实是希望在支付时候自己账户没有钱，但是余额有钱的状态下，不需要操作退出页面去提现这步，就可完成付款。**最主要目的是：不要退出这个页面就可以完成付款。**
## 解决思路
- 交易产生的log最好是能记录在链上，而不需要去翻用户log。
- 先提现后赞赏可以保证交易数据都是在链上可查的。
## 解决方案
- （在没有支付宝等第三方支付手段可选的情况下）那么我们可以改变UX：用户点击赞赏后，提示：“您的账户余额不足，您还有4.5EOS待提现。是否立即提现？”。确认提现后，在页面中就可完成提现操作。然后弹出赞赏信息输入窗口。
- （在有多种同时可选择的第三方支付手段情况下）那么比上述步骤增加一个选择支付渠道的流程。

**Comment by lychees** [comment]
只是提出来，现在肯定不做。
