### ISSUE TITLE
【评论】偶尔出现的重复评论

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#403]
**出现环境**：Prod版本

<img width="614" alt="屏幕快照 2019-04-17 上午11 14 27" src="https://user-images.githubusercontent.com/2507027/56258408-0f895c80-6102-11e9-8abe-26fd8eb916d9.png">

**Comment by xiaotiandada** [comment]
应该是这里滚动了两次 我来fix把
