### ISSUE TITLE
【编辑文章】编辑文章后元数据错乱的 bug 

### ISSUE THREAD

**Issue by aDappDeveloper** [smart-signature/smart-signature-future#413]
**操作系统**：macOS 
**浏览器**：Chrome浏览器
**钱包版本**：Scatter桌面
**出现环境**：https://staging.smartsignature.io/

**描述这个bug**
生产环境原文：https://smartsignature.io/article/QmceVm4Wi5vLfh5ZfzLmJ3mR1YcMcLAgJeAvHDjmCnSzwU

在 Staging 环境重新编辑后，链接为：
https://staging.smartsignature.io/article/QmUiVWUpZA3cdFdXHDW4KZFFARfxP4gycqX8rSWqRsitvo

Bug 有：
- [ ] 编辑完同时弹出 成功 & 失败 弹框
- [ ] 元数据丢失（日期、阅读量、IPFS Hash）
- [ ] 赞赏队列丢失
- [ ] 点击分享按钮，复制分享文案无法取得元数据（文章名、作者）：

![bug3](https://user-images.githubusercontent.com/44354447/56306105-4bf5a080-6174-11e9-8372-b4ba777f3410.png)

<img width="353" alt="bug1" src="https://user-images.githubusercontent.com/44354447/56305858-a7735e80-6173-11e9-930e-8954d36ea551.png">

<img width="548" alt="bug2" src="https://user-images.githubusercontent.com/44354447/56305960-ef928100-6173-11e9-9f15-ae0d763a5d3a.png">

《undefined》by undefined 
https://staging.smartsignature.io/article/undefined?invite=andoromedaio
赞赏好文，分享有收益 ！

**Comment by guanchao71** [comment]
![image](https://user-images.githubusercontent.com/10827774/56308639-66cb1380-617a-11e9-9307-c19ef95130fd.png)

**Comment by yukiexe** [comment]
關於 3. 就是 #343

**Comment by yukiexe** [comment]
關於 2. ，comment 並沒有提前放了，而是等到轉帳的異步結束之後才執行發送，但是只等異步結束而不是看其結果來判定。

並且，sendComment 中才會去檢查 access token ，失效或沒有會跟用戶要簽名，要是用戶拒絕了，那 sendComment 失敗，並且因為轉帳已成功會造成吞幣
需要在讚賞一開始就檢查 access token 去做處置

https://github.com/smart-signature/smart-signature-future/blob/a58876bd28437f9635a89e54f97f3cdec7a97b82/src/views/Article/index.vue#L398-L403

**Comment by guanchao71** [comment]
当问题复现的时候：
![access token bug](https://user-images.githubusercontent.com/10827774/56404957-43988500-629c-11e9-9743-553024d2f9a5.png)

**Comment by AkemiKusane** [comment]
在新版中，上述问题可以通过退出登录的方式来解决。
