### ISSUE TITLE
【代码优化】使用公用的组件替换原来的分页功能

### ISSUE THREAD

**Issue by xiaotiandada** [smart-signature/smart-signature-future#417]
替换现有的分页功能 使用公用的组件
---
- [x] 我的文章页面
- [x] 我的赞赏页面
- [x] 他人主页列表显示
- [x] 资产明细列表
- [x] 粉丝、关注列表
- [x] 赞赏队列

公用组件地址 @/components/PullComponents.vue

**Comment by yukiexe** [comment]
既然這個組件這麼多地方要用，可以用自動化組件註冊，名字叫 Base_____.vue 放在 components 裡就可以了，這樣不用每一頁都加上 import 和在 components 裡加上

**Comment by xiaotiandada** [comment]
> 既然這個組件這麼多地方要用，可以用自動化組件註冊，名字叫 Base_____.vue 放在 components 裡就可以了，這樣不用每一頁都加上 import 和在 components 裡加上

好嘞
