### ISSUE TITLE
【界面/模块】文章赞赏状态Bug

### ISSUE THREAD

**Issue by xiaotiandada** [smart-signature/smart-signature-future#423]
**操作系统**：Windows / macOS / 安卓 / IOS
**浏览器**：Chrome浏览器/微信浏览器/TP钱包浏览器
**钱包版本**：Scatter插件（版本号）/Scatter桌面（版本号）/TP钱包（版本号）……
**出现环境**：Prod版本/Test环境/本地环境

**描述这个bug**
用一句简洁明了的语言来描述这个bug

因为赞赏状态是通过赞赏列表来判断的，所以如果自己不在第一页里 则无法正常显示状态

**复现流程**
任一一篇文章， 自己不在赞赏列表第一页的

**预期结果**
用一句简洁明了的语言来描述你期望的结果是什么

正常显示赞赏状态

**问题截图**
如果可能，请尽量插入截图来描述问题

![image](https://user-images.githubusercontent.com/24250627/56416903-de0cbe80-62c4-11e9-8bc2-c072eb6537f7.png)

**备注信息**
你可以在此处写下任意备注内容

**Comment by guanchao71** [comment]
已转移
