### ISSUE TITLE
【界面/模块】首页不显示个人信息和无法跳转主页Bug

### ISSUE THREAD

**Issue by xiaotiandada** [smart-signature/smart-signature-future#424]
**出现环境**：Test 环境

**描述这个bug**
首页不显示个人信息和无法跳转主页Bug

**复现流程**
1. 直接打开首页查看即可

**预期结果**
用一句简洁明了的语言来描述你期望的结果是什么

正常显示用户信息和跳转

**问题截图**
如果可能，请尽量插入截图来描述问题

![image](https://user-images.githubusercontent.com/24250627/56453215-b162b080-6371-11e9-810e-8efae5487f7e.png)

**备注信息**
你可以在此处写下任意备注内容

**Comment by lychees** [comment]
<img width="390" alt="屏幕快照 2019-04-20 下午2 21 19" src="https://user-images.githubusercontent.com/2507027/56453625-b0348200-6377-11e9-8f09-1b0be1b5aaf4.png">

Same here，应该和昨晚 [#390](https://github.com/smart-signature/smart-signature-future/pull/390) 最后的解决一下冲突有关。

**Comment by AkemiKusane** [comment]
#426  check
