### ISSUE TITLE
【文章状态】文章可见度的设计

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#432]
# 开发需求清单
文章状态包括：
- [x] 公开 Public
- [ ] 私密 Private，仅自己可见，即为草稿箱。
- [ ] 限制 Restricted，仅关注我的粉丝可见

这个功能可以有效增加关注功能的使用场景，并为今后粉丝币做准备。

**Comment by AkemiKusane** [comment]
要不要考虑加个（广告）状态
然后加了这状态的文章会自动随机粗线在文章列表里面

**Comment by Kumo-YZX** [comment]
感觉加广告会有点影响文章质量的平衡性

**Comment by lychees** [comment]
> 要不要考虑加个（广告）状态
> 然后加了这状态的文章会自动随机粗线在文章列表里面

先简化需求。

**Comment by guanchao71** [comment]
已转移
issues/18
