### ISSUE TITLE
【用户页】丰富用户信息

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#436]
- [x] 邮箱 ( 这个功能在 prototype 版本里就有，用来接收 `steamKey`，目前已经把字段从 `mail` 改成了 `email`，后端我参考了 `nickname` 的实现已经 `implement`，正在测试中。
- [x] 个人简介。
- [ ] 绑定 github。
- [ ] 绑定 twitter。
- [ ] 绑定 wechat。

**Comment by guanchao71** [comment]
隐私不是我们的特性之一么？为什么又要开始绑定这些内容了？

**Comment by lychees** [comment]
> 隐私不是我们的特性之一么？为什么又要开始绑定这些内容了？

绑定后可以选择不可见。
比如如果我要从第三方平台搬运文章，那么你必须要绑定相应的账户，才能证明这篇文章是我发表的。
这样就可以杜绝各种盗版。

而设置 Email 地址是之后接收 steamKey，和密码恢复的需要，也是早晚都会加上的功能。

**Comment by guanchao71** [comment]
已转移
https://andoromeda.coding.net/p/smart-signature-future/requirements/issues/48

**Comment by lychees** [comment]
没有 CI 之前我们无法使用 coding。

**Comment by yukiexe** [comment]
但是 issue 可以移過去討論
