### ISSUE TITLE
穩定幣的運用

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#47]
下期功能建議

透過穩定幣能夠去除額外的波動風險

文章傳播時程可分成，長期、中期、短期
短期就是所謂的爆紅文章，這部分用 eos 快收快提現問題不大

問題是中期長期的文章作者，不會希望整天盯著幣價去做資產調動，太麻煩了，只需專心寫作多美好。這部分的作者就會希望他獲得的文章收入能夠不隨幣價波動，很適合用穩定幣

實際技術上實現問題也不大，可以分成自己弄一套穩定幣系統或是引用其他穩定幣，後者是相當簡單的。

先在這裡提了，避免忘了

**Comment by lychees** [comment]
传销是区块链的皇冠。
稳定币是区块链的珍珠，

**Comment by yukiexe** [comment]
先 close ，以後要加再打開
