### ISSUE TITLE
打赏输入框的正则检验。

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#48]
- **在输入金额窗口没有进行正则验证，可以输入奇怪的内容**

![image](https://user-images.githubusercontent.com/10827774/54521274-8ddccc80-49a5-11e9-807e-dc09628ce49b.png)

- **确认交易后会打赏失败**

![image](https://user-images.githubusercontent.com/10827774/54521249-80bfdd80-49a5-11e9-9058-c8d312b852e0.png)

**Comment by yukiexe** [comment]
@floatj 正则验证給你加一下，有看到在下面回

**Comment by yukiexe** [comment]
support() 的流程在此解說一下：

1. 跳框問打赏金额
2. 發文章的hash到後端查 sign id
3. 把參數打包進對 eosio.token 發 transfer action 中
4. 錢包跳確認

圖中的報錯是合約有個 0.1 EOS 才能打賞的限制，不是我加，不知道要不要去掉
@lychees

如果是 0.1 EOS 限制造成的話，應該沒其他問題了， @guanchao71 可以再測一次

**Comment by yukiexe** [comment]
有空的話錯誤訊息可以弄得親人一點...
我去參考隔壁項目好了

經驗談是一定會有用戶截圖問錯誤訊息，如果好看一點處理起來就快，用戶感受也會好一點

**Comment by lychees** [comment]
我觉得这个不算 bug 吧。。。（（

**Comment by yukiexe** [comment]
done by #67 https://github.com/smart-signature/smart-signature-EOS-contract/commit/e32d75ad1853e80225f6f50c66616eafac93b1f0
