### ISSUE TITLE
个人资料模块

### ISSUE THREAD

**Issue by frankwei98** [smart-signature/smart-signature-future#5]
- [x] 设计向设计稿靠拢
- [x] follow / unfollow

**Comment by yukiexe** [comment]
應該用得上
https://zhongantecheng.github.io/zarm-vue/#/documents/nav-bar

**Comment by frankwei98** [comment]
+1

咚咚 <notifications@github.com>于2019年3月8日 周五上午12:28写道：

**Comment by yukiexe** [comment]
User.vue 其中一個模塊 Asset.vue 草稿版已經上線 #22 ，在此註記一下

**Comment by Deasoso** [comment]
我来吧，按照原定分工来。

**Comment by Deasoso** [comment]
前端已经基本完成，等待后端ready后补全功能。

**Comment by yukiexe** [comment]
有些更新關於 User.vue 
#25 #26

**Comment by lychees** [comment]
>       <Button class="rightbutton" size="small" type="success" ghost @click="edit">
>         <div v-if="username === currentUsername">编辑</div>
>         <div v-else>关注</div>
>       </Button>

当按钮显示为 “关注” 时，单击仍然会执行 “编辑” 的逻辑。
在后端 API 到来之前，此处可以先 alert("关注")。

**Comment by Deasoso** [comment]
update
#55 #65 
页面已基本完成，功能等待后端补全测试

**Comment by yukiexe** [comment]
後端 follow / unfollow 的api出了，你看一下，沒問題就加上吧
@Deasoso

**Comment by Deasoso** [comment]
follow / unfollow 功能已经可以使用。

**Comment by Deasoso** [comment]
已打赏过的文章列表完成。
至此个人资料模块页面与功能已齐全。
