### ISSUE TITLE
文章被阅读次数统计

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#51]
运营大大提到统计文章阅读次数非常重要，配合文章打赏总金额是给用户做决策的重要数据依据。
- 记录一篇文章被多少位登录用户阅读过。
- 每个用户只记录1次。
- 需要后端记录每个用户的阅览记录，在进入文章的时候，文章计数器验证该用户是否打开过该文章，如果没有则计数器+1-->&用户阅览记录+1。
- --->由此其实是实现了一个阅览记录查询功能（可以不公开给用户自己查看）。
- 这部分日志数据记录下来对未来我们发展可能会有帮助，。
但是如果我们在后端记录用户阅读记录是不是违反了某些隐私条例

**Comment by guanchao71** [comment]
如果我们不去记录哪些用户看过这篇文章似乎会更简单一些？统计这篇文章被任意用户打开任意次数的累加。存在会失控的可能性。

**Comment by guanchao71** [comment]
@lychees @ganjingcun @yukiexe 来说说想法呗

**Comment by ganjingcun** [comment]
可以在article页面的，加个一个静默的http数据上报请求。数据大概包含文章、用户

**Comment by yukiexe** [comment]
1. 有登陸的人開起文章才會發送紀錄給後端
2. 每次開啟都發送
3. 由後端過濾掉記錄過的
4. 不公開的話就沒事了

加個 js func 讓前端 call，call 就是發送，功能就是 2. ，需要的資訊放參數，前端會填
放在... backend.js 裡
每次開啟或是要確認登陸這部份邏輯給前端做

**Comment by guanchao71** [comment]
结论：当前版本做阅读次数的显示不要进行真实用户过滤（未来再考虑，先让数据好看）。用户无需登录反复打开页面，每次都计数。

**Comment by ganjingcun** [comment]
done whit this commit : https://github.com/smart-signature/smart-signature-backend/commit/d114c135040ab363a35f3d2bb13d6514b32e322f

**Comment by yukiexe** [comment]
Doc:
https://github.com/smart-signature/smart-signature-future/issues/114#issuecomment-475184265

**Comment by yukiexe** [comment]
@Deasoso 給你加一下？

**Comment by Deasoso** [comment]
> @Deasoso 給你加一下？

ok

**Comment by Deasoso** [comment]
> @Deasoso 給你加一下？

https://github.com/smart-signature/smart-signature-future/pull/188
