### ISSUE TITLE
资产明细，進度 90%

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#52]
from #45

- [x] 当前未提现的余额

- [x] 历史写作总收入，历史转发总收入，历史打赏总支出

需要後端記錄，合約只記錄当前未提现的余额
這種總額性的資料寫在合約裡其實成本上也算便宜，考慮到伺服運營成本攤在每筆資料上的話

new -> 新進度是靠前端寫完了，後端 copy 過去寫入 db ，之後弄個調用 db 的給前端就行

- 历史明细列表
  - [x] 交易金额
  - [x] 交易方向（收/支）
  - [x] 交易完成时间
  - [ ] 文章标题预览

- 提现
  - [x] 点击提现按钮 -> 弹出提现窗口
  - [ ] 勾选同意提现规则之后才能点击提现按钮
  - [x] [合約測試 passed] 能够正确提现余额到EOS账户里面

#49 資產頁面能正確抓到 income 訊息

**Comment by yukiexe** [comment]
- 当前未提现的余额
- 历史写作总收入，历史转发总收入，历史打赏总支出

需要後端記錄，合約只記錄当前未提现的余额
這種總額性的資料寫在合約裡其實成本上也算便宜，考慮到伺服運營成本攤在每筆資料上的話

- 能够正确显示历史明细列表
  - 交易金额
  - 交易方向（收/支）
  - 交易完成时间
  - 文章标题预览

還要改一下 css

- 点击提现按钮后弹出提现窗口
- 当输入完金额和交易密码之后并且勾选同意提现规则之后才能点击提现按钮
- 能够正确提现余额到EOS账户里面

哎呀，都是布局問題

**Comment by yukiexe** [comment]
#70 #61 #55 #54 #49

**Comment by yukiexe** [comment]
#73

**Comment by guanchao71** [comment]
> #73

![image](https://user-images.githubusercontent.com/10827774/54607937-90fdb880-4a8a-11e9-93b4-0573f76abc25.png)
似乎是符号写错了？我记得应该是我打赏了0.1EOS而不是收入0.1EOS。我打赏的应该写作：-0.1EOS

**Comment by yukiexe** [comment]
當然是因為符號根本還沒加啊

> 交易方向（收/支）

我可沒打勾

**Comment by yukiexe** [comment]
#87

**Comment by yukiexe** [comment]
当前未提现的余额 #95
// 集中力要用完了 w

**Comment by yukiexe** [comment]
#115

**Comment by guanchao71** [comment]
>   - [x] 交易完成时间

@yukiexe 目前显示的时间仍然不正确，相差8个小时。猜测是因为选用的时区问题。中国是+8时区，所以最少显示成了8小时。
![image](https://user-images.githubusercontent.com/10827774/54742553-b90d2900-4bfc-11e9-8235-660bf8c43684.png)
**解决方案：根据用户的语言切换时区。当前默认都是中国用户。**

**Comment by yukiexe** [comment]
#140

**Comment by guanchao71** [comment]
这是3月23号来测出的部分需要修改的地方：
1. - [ ] **显示待提现余额**

当前未能正确显示待提现的余额数量。一直显示为0.
预期结果：正确显示当前合约里待提现的余额数量。

2. - [ ] **资产明细页面的收入和支出额度显示数据超长**

当前个人资产明细页面的收支统计显示最多居然达到了小数点之后16位（看下图）
预期结果：最多显示小数点后4位（目前的赞赏精度是0.0001EOS）

3. - [ ] **在个人页面显示正确的收益额**

当前个人主页显示的赞赏收益和写作收益与资产详情页面中显示的对应数据不符。
![image](https://user-images.githubusercontent.com/10827774/54864082-94e05200-4d8c-11e9-830b-8db682088e7d.png)
![image](https://user-images.githubusercontent.com/10827774/54864103-ec7ebd80-4d8c-11e9-91a2-a91a536b33db.png)
预期结果：在个人主页中能够正确显示和资产详情页面对应的：赞赏收益和写作收益的数据，小数点后最多显示4位（目前的赞赏精度是0.0001EOS）

**Comment by guanchao71** [comment]
- [ ] **通过别人的邀请链接给自己文章点赞并发症**
- 现在作者通过别人的邀请链接打赏自己的文章，钱会给到作者自己。这种处理方式显然是不合理的，相当于增加了一条额外的打赏规则，增加了用户的理解成本（如无必要，勿增实体）。
- 并且发出邀请链接的用户会在资产明细中收到神秘的+0.0000EOS，并且虽然是+号，但是却显示为了绿色（正常绿色代表支出）非常难以理解。

![image](https://user-images.githubusercontent.com/10827774/54878261-2ae7ab80-4e65-11e9-900a-3ea60e8027f4.png)

**Comment by guanchao71** [comment]
### 当前创作收益和赞赏收益两项数据没有正确显示：
- 创作收益显示的其实是待提现余额，而且没有*精度系数，显示的是个很大的数字
- 赞赏收益直接没有显示
![image](https://user-images.githubusercontent.com/10827774/54878602-ef031500-4e69-11e9-9abf-0e8f42af5d1f.png)

### 预期结果
1. - [ ] **创作收益数据显示包含：**
- 用户A直接访问问文章链接，赞赏的所有钱都属于作者的创作收益
- 用户A通过作者的邀请链接访问文章，赞赏的所有钱都属于作者的创作收益
- 用户A通过用户B的邀请链接访问文章，赞赏满足B的quota之后，溢出的赞赏资金都属于作者的创作收益

2. - [ ] **赞赏收益数据显示包含：**
- 用户B通过用户A的邀请链接进行赞赏，在用户A的收益范围中的部分都算作赞赏收益

重点总结：收益归到哪个种类主要是看收益来源的文章作者是不是自己？如果是自己那就是创作收益，如果不是自己那就是赞赏收益。
