### ISSUE TITLE
[Bug] 资产明细页面的 UI bug

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#53]
![圖片](https://user-images.githubusercontent.com/3849019/54532066-d7d3ab80-49c1-11e9-9af7-f800633dca2d.png)

他會產生如下效果
![圖片](https://user-images.githubusercontent.com/3849019/54532131-02256900-49c2-11e9-9e18-56d017828065.png)

**Comment by guanchao71** [comment]
看起来有点好笑，，，这是蓝湖的标注信息么？

**Comment by yukiexe** [comment]
是啊，藍湖是可以直接產生 css 的，然後因為畫面小這個 bug 就沒有顯現(文字自動擠在一起了)
然後我複製css過去用就發現這個 bug lol

**Comment by yukiexe** [comment]
反正這裡通知不到 UI
