### ISSUE TITLE
[delay] 搬运文章，進度 0%，轉交另一 team

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#58]
我沒頭緒，之前你們說基本要有哪些？
有任何討論記錄嗎？

**Comment by lychees** [comment]
某个上古版本的基于 Ethereum 的 Prototype 中，有 implement 过这个功能。
https://github.com/smart-signature/sponsor-token-website/blob/master/src/views/CreateItemView.vue

至少我记得可以搬运 知乎 的文章。

**Comment by guanchao71** [comment]
delay，交给浩哥和公司前端组来接手。

**Comment by guanchao71** [comment]
要点：
1.扒html得转换成markdown，如果不能够完美，需要趴下来纯文本。
2.限制搬运链接来源
3.图片怎么搬过来
4.搬运后要加上预览和编辑步骤（就是编辑文章的页面）
5.后期要考虑搬运文章的时候如何验证作者身份
暂时可以想到这些

**Comment by guanchao71** [comment]
先导版本里面的显示就已经遇到markdown渲染的坑了。这是个不小的问题，需要认真对待。
