### ISSUE TITLE
关注系統，目前進度 95%

### ISSUE THREAD

**Issue by yukiexe** [smart-signature/smart-signature-future#60]
來個人提個流程

**Comment by lychees** [comment]
This issue should be delegated to @ganjingcun.

**Comment by guanchao71** [comment]
- 当我点击关注之后，我的关注人数+1，对方的粉丝人数+1.
- 当我点击取消关注之后，我的关注人数-1，对方粉丝人数-1.
- 当前版本没有查看关注列表的功能，只提供：关注&取消关注

**Comment by yukiexe** [comment]
歐，我說的是資料流的流程

**Comment by Deasoso** [comment]
https://github.com/smart-signature/smart-signature-backend/issues/1
其它都做好了，等弄完一起提pr

**Comment by lychees** [comment]
<img width="777" alt="屏幕快照 2019-03-22 上午2 07 56" src="https://user-images.githubusercontent.com/2507027/54774773-7290ec00-4c47-11e9-995d-8be63e4a3068.png">

关注失败。

**Comment by Deasoso** [comment]
> <img alt="屏幕快照 2019-03-22 上午2 07 56" width="777" src="https://user-images.githubusercontent.com/2507027/54774773-7290ec00-4c47-11e9-995d-8be63e4a3068.png">
> 
> 关注失败。

fixed

**Comment by guanchao71** [comment]
记录下：当前实现的是最基础的关注和取消关注功能。并且可以在个人页面显示正确的粉丝数和关注人数。
目前没做的是：关注列表和粉丝列表。统一化管理fo和unfo
