### ISSUE TITLE
提现时候是一次全部提走还是可以选择提走多少

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#64]
> 提现金额过大-->超出最大提现金额

@guanchao71 
提現不是按一次提全部，這樣的功能嗎？

合約端通知用 @lychees

_Originally posted by @yukiexe in https://github.com/smart-signature/smart-signature-future/issues/45#issuecomment-474011988_

**Comment by yukiexe** [comment]
拒絕选择提走多少的功能，太麻煩，前端配合還一堆工作量，而且用途太低。
目前也沒有留存餘額的必要，打賞也不能從餘額扣，也不會出這樣的功能。

**Comment by yukiexe** [comment]
我玩遊戲從交易所提錢也從來沒有選擇提多少的功能，要是有我會煩死。
留在裡面也沒利息，合約帳戶還有保管金額的風險，全部一次提走最好。

**Comment by lychees** [comment]
一次提走即可。（想啥呢。。

**Comment by guanchao71** [comment]
OK ，i approve.
