### ISSUE TITLE
内建返回功能

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#69]
当我copy文章链接到别的浏览器打开，点击内部的返回按钮是直接调用了浏览器的返回功能。
我们的返回流程是如下的（即便是分享页面别人打开获取的独立页面，也是遵循下面的流程返回）：
**二级文章页面**
内部+外部：打赏列表--返回-->文章页--返回-->首页
**四级文章页面**
内部：从我的支持/创作文章列表进入4级文章页面--返回-->返回到列表
外部：4级文章页面--返回-->直接回到首页

**Comment by yukiexe** [comment]
被抓包只有调用浏览器的返回功能了

**Comment by guanchao71** [comment]
我有更好的想法了。
