### ISSUE TITLE
[Bug] 图片替换术bug

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#76]
![image](https://user-images.githubusercontent.com/10827774/54600598-1af05600-4a78-11e9-84e0-9a80cb864dc0.png)
![image](https://user-images.githubusercontent.com/10827774/54600606-1e83dd00-4a78-11e9-9d1c-96ff8efe2ea3.png)
我在编辑器里面插入图片，然后不发布退出，再点击这篇文章，原本加载不出来的图片就变成我刚才插入的图片了，，，

**Comment by yukiexe** [comment]
這個叫做暫存圖片復用，因為存儲都是同一個暫存圖片導致的(個人推估)
插件的開發者才好改
說起來算bug嗎？瀏覽器有意為之的樣子...

**Comment by frankwei98** [comment]
因近段时间没有类似的报告，以后有任何重现再 reopen
