### ISSUE TITLE
全局 referral 的 bug

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#79]
当我用用户 A 的推荐链接打开文章 P 时。
下次使用空的推荐链接打开文章 Q，在打赏时，也会带用户 A 的推荐链接。

Maybe this is a feature.

**Comment by yukiexe** [comment]
只寫了半套，這樣寫功能不靠譜啊

![圖片](https://user-images.githubusercontent.com/3849019/54604249-41ff5580-4a81-11e9-95b7-5e2376318780.png)

**Comment by yukiexe** [comment]
#80
