### ISSUE TITLE
我的收入未能正确显示。

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#82]
<img width="580" alt="屏幕快照 2019-03-19 下午8 29 36" src="https://user-images.githubusercontent.com/2507027/54606105-d370c680-4a85-11e9-8598-f95eda20df2d.png">

<img width="1018" alt="屏幕快照 2019-03-19 下午8 29 24" src="https://user-images.githubusercontent.com/2507027/54606107-d53a8a00-4a85-11e9-908f-ceb720d38126.png">

正确显示应该为，0.1 eos，0.1 eos。（且左边支持收入应该为创作收入？）

**Comment by yukiexe** [comment]
這件事很有趣，跟昨天早上的蓋版有關，我沒有去動他寫出來的所以...
