### ISSUE TITLE
导航栏 redesign

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#83]
之前设计的页面跳转现在看起来是有问题的。返回功能直接调用了浏览器的返回，会导致逻辑有点混乱。如果我打开别人粘贴给我的文章链接，我点击返回应当是回到首页而不是退出了当前页面。。

我希望的路径是看完文章，返回到首页，再返回时候退出。但是如果要设计内部返回操作就很复杂，所以考虑现在页面不多，首页是所有内容入口，给用户的导航直接就是回到首页。如果要用浏览器的返回，那不直接用浏览器自带的就好了，我们也没必要加个按钮~。
这个是我之前没有考虑到的

**我的修改建议：**
- 页头：logo图标-->首页，页面标题。
- 页脚：首页按钮，我的主页按钮（未登录时候隐藏）

前端先行，设计后续要跟上

**Comment by guanchao71** [comment]
@frankwei98 将head改为首页导航之后体验upup。
下面提几点改进的点point：
- [ ] head部分置顶显示，不随页面滑动。
- [ ] 文章页面的右上角share功能暂且去掉，并且在所有的子页面中应用。（蓝湖中已改）
    - [ ] 文章详情页面
    - [ ] 个人主页
    - [ ] 他人主页
    - [ ] 资产明细
    - [ ] 我的原创文章页面
    - [ ] 我的打赏文章页面
    - [ ] 规则说明页面
- [ ] 在文章详情页的右上角加入“详细规则”按钮（蓝湖中已改）-->点击跳转到规则页面。

**Comment by guanchao71** [comment]
测试gitter

**Comment by yukiexe** [comment]
#181

**Comment by yukiexe** [comment]
> head部分置顶显示，不随页面滑动。
> 所有页面的head横向自适应宽度

這兩者應該有達成？有問題請提出

> 文章页面的右上角share功能暂且去掉

已去掉

> 文章详情, 规则说明

已應用統一化 Header
