### ISSUE TITLE
点击链接后页面要进行视角转换

### ISSUE THREAD

**Issue by guanchao71** [smart-signature/smart-signature-future#84]
**显示页面信息的时候没有做视角转换：**
当我copy我的文章列表页面url给别人，别人点击后打开的理应是“他人主页”，但是实际上别人看到的是和我一样的页面（我看到自己的三级页面样式）。
目前我的个人资产页面就是可以被别人替换域名里的名字来直接访问的。

--(草稿箱feature)--

**Comment by lychees** [comment]
啥问题啊。。。。= =

**Comment by yukiexe** [comment]
忽然想到 FB 有這種 bug 過
