### ISSUE TITLE
一个用户对一篇文章只能打赏一次 进度90%

### ISSUE THREAD

**Issue by lychees** [smart-signature/smart-signature-future#94]
为了简化需求，目前合约的设计师一个用户对一篇文章只能打赏一次。
需要前端进行提示，当文章已经打赏过时，打赏按钮应处于 disable 状态。

**Comment by yukiexe** [comment]
有做啊？
只是打賞过的狀態還沒抓，在個別功能進度列表那邊有寫

**Comment by yukiexe** [comment]
#24

**Comment by yukiexe** [comment]
#102

**Comment by guanchao71** [comment]
在第一次打赏之后按钮不能自动切换状态，需要我再点击一次打赏按钮之后才会切换，但是会进入下一次签名的流程--->确认后报错

**Comment by guanchao71** [comment]
打赏界面没有退出按钮呢？

**Comment by yukiexe** [comment]
> 打赏界面没有退出按钮呢？

補了
