### ISSUE TITLE
👛手机钱包登录问题

### ISSUE THREAD

**Issue by aDappDeveloper** [smart-signature/smart-signature-future#96]
直接从手机钱包（Tokenpocket为例）进入文章页面（如https://sign-dev.dravatar.xyz/article/Qmf7JV1VJp7G9tL8LRrNtDwqekaZpTqRJfdHXNS1kNvXYv?invite=minakokojima） 
之后不能自动登录，要跳转到首页才能登录。从首页登录之后再进文章就没有邀请信息了

**Comment by yukiexe** [comment]
之後每個頁面要一起修，統一一下這問題

**Comment by yukiexe** [comment]
這很重要

**Comment by yukiexe** [comment]
這部分產品要出一個模擬用戶進出各個頁面的流程 @guanchao71

**Comment by guanchao71** [comment]
**需要测试下在不改变功能的前提下，能不能完成以下步骤：**
1. 复制邀请链接到TP钱包中打开，未登录，无法打赏
2. 点击主页按钮后回到首页，点击登录，正确登录
3. 点击浏览器返回按钮，回到文章页，保持登录状态，并且url中依然记录了邀请链接

**如果不能完成：**
- 需要在文章的赞赏和分享按钮中加入登录检测
- 如果点下按钮时候没有登录，则自动登录，如果无法登录则弹出错误提示：请在‘TP’钱包中打开邀请链接。如果可以登录则自动登录然后直接开始打赏流程。
