### ISSUE TITLE
 编辑预览时与发布文章格式不一致

### ISSUE THREAD

**Issue by aDappDeveloper** [smart-signature/smart-signature-future#97]
编辑时的Markdown预览与发布后不一致，如该篇文章 https://sign-dev.dravatar.xyz/article/QmTDCaWX2GsFvNfmrA5oxmeo3KgGNYnx7nD41ApfjUgniC

1、上传的图片没有显示
2、段落间距有差别
3、链接不能点击（应该是作者Markdown语法写的不对）
4、表格有问题（和在编辑界面预览的效果不一样）
5、Bullet 多出来了空行 （预览的时候没有）

**Comment by yukiexe** [comment]
這其實是 css 顯示問題，因為發出去的是 Markdown ，不包含 css 的段落间距等等
然後預覽格的 css 跟文章顯示用的並沒有做一致性調整
文章顯示用的還是從 telegra.ph copy 來的

**Comment by aDappDeveloper** [comment]
除此之外，从手机钱包阅读，排版更加怪异

**Comment by guanchao71** [comment]
- 前端对markdown的样式解析不正确，比如markdow
- 页面边距设置不正确，整体效果设置参考蓝湖设计稿。
- 图片上传测试可以，疑问是不是大小限制？
- 需要在手机浏览器上简化markdown编辑按钮--->仅保留图片上传、和眼睛切换视图，默认为单窗口显示。

**Comment by guanchao71** [comment]
这块处理起来可能会有难度，及时沟通讨论。

**Comment by yukiexe** [comment]
可能造成問題的元兇
https://github.com/smart-signature/smart-signature-future/issues/145#issuecomment-475581768

**Comment by yukiexe** [comment]
現在可以再測測看

**Comment by yukiexe** [comment]
=> #185

**Comment by guanchao71** [comment]
4月3号，张翔已经基本完成。可以先关闭了。
